### ISSUE TITLE
Some rooms become much warmer than other rooms on a single floor and A/C doesn't get triggered

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#1015]
Tech investigation for https://github.com/kinu-garage/30y-130s_life/issues/1320

Related to https://github.com/kinu-garage/hut_10sqft/issues/852

Problem might be very similar to what's discussed in [community.home-assistant.io/#387147](https://community.home-assistant.io/t/multi-room-temp-inputs-to-one-thermostat/387147).

## Things to try
- [x] AC Infinity AIRTAP T4 -> https://github.com/kinu-garage/hut_10sqft/issues/1015#issuecomment-2843198477
- [ ] Figure out if Keen Smart vent can be integrated into HASS?
   - [ ] Custom HASS component: [aglehmann/home_assistant_ecovent](https://github.com/aglehmann/home_assistant_ecovent)
   - [ ] What do those people in [community.home-assistant.io#878717](https://community.home-assistant.io/t/keen-vent-cover-entity-no-longer-working-after-2025-4-2/878717) use in order to access the device?

**Comment by 130s** [comment]
Pure software solution is discussed in the linked thread but doesn't seem to have materialized yet.

Meanwhile, interested in h/w solution e.g. https://keenhome.io/products/smart-vent

Apparently there are multiple threads in hass comm e.g. https://community.home-assistant.io/t/using-multiple-sensors-to-control-single-thermostat-which-method-thermostat/311553

**Comment by 130s** [comment]
[Master toilet](https://photos.google.com/photo/AF1QipOXunC7sI0YQ7PiPRSZC9Pirt9CFjqvc1s9umBe): <s>w 11 6/8 inches, h 5.5 inches</s>
[Master bath above sink](https://drive.google.com/file/d/13u6PcBAwHfpVRylzE2ZebMjxprgEF1EI/view?usp=drive_link): <s>w 13 6/8 in, h 5 7/8 in</s>

Oops. I have to redo measuring as according [to flair.com](https://flair.co/products/vent?currency=USD&gad_source=1&gclid=Cj0KCQjw2a6wBhCVARIsABPeH1sdpEX185vv_-5hH3UFn6Q4zEf6Q44Zz40-9hhs1g5z_zU72WW3uNQaAk8gEALw_wcB) the measurement in need is the size of the vent, not the cover. Backed by [keenhome.io](https://keenhome.io/pages/how-do-i-measure-my-vent-sizes-1_) as well.

> HOW TO MEASURE VENTS
> 
> 1. Remove your existing vents
> 2. Measure the existing hole (not the vent cover)

- Flair: [Official comment from 2019](https://support.flair.co/hc/en-us/community/posts/360053132711-Hubitat) says flair is not zigbee/z-wave :/
- keenhome.io: Lots of sizes are out of stock. https://keenhome.io/products/smart-vent-pro shows only 4x12, 6x14

Also read https://www.reddit.com/r/homeassistant/comments/w87cfs/smart_vents/

**Comment by 130s** [comment]
Measured the vent at the master bathroom, [12.5 in x 3.75 in](https://drive.google.com/file/d/1C_pCOxodjmTjSIiOspLOkL0t1fFw2RMg/view?usp=drive_link). I don't find the exact size on [Smart Vent Pro on Keen](https://keenhome.io/products/smart-vent-pro). The [video Flair made](https://youtu.be/9H6GYn1c_C0?si=zeqoIcg9AtN6hTVC&t=50) suggests that the duct openings can vary by a quarter or by half inch. With that, 12 x 4 vent should fit.

Then, keen's web page inconsistently shows often 4x12 available and often not. I cannot add one to cart. Ok it's fair to assume Keen is out of business according to [this article (slashgear.com)](https://www.slashgear.com/1385116/what-happened-keen-home-smart-vents-shark-tank-season-6/).

Found [Ecovent Smart Wall Vent](https://www.discounthomeautomation.com/Ecovent-Smart-Wall-Vent-ENEVWx?quantity=1&custcol2=165) that supports zigbee and 4x12in.

**Comment by 130s** [comment]
I cannot find who's the manufacturer of Ecovent products. Turned out Ecovent started in early 2010s then looks like they got merged [by Keen (keenhome.io)](https://keenhome.io/blogs/community/how-keen-home-and-ecovent-joined-forces#:~:text=Ecovent%20(now%20a%20Keen%20Home,to%20see%20what%20comes%20next.))...

That said I went ahead giving a try [ecovent smart vent](https://www.homecontrols.com/Ecovent-Smart-Ceiling-Vent-ENEVCx).

**Comment by 130s** [comment]
Asked https://diy.stackexchange.com/questions/299859

**Comment by 130s** [comment]
SE forum ends up with "no Zigbee". Then I found [someone said](https://community.home-assistant.io/t/hvac-smart-vent-zoning-control-through-homeassistant-no-internet-required-but-recommended/440051/15) Keen works with Zigbee, so I'm asking for [a clarification](https://community.home-assistant.io/t/hvac-smart-vent-zoning-control-through-homeassistant-no-internet-required-but-recommended/440051/21).

Another approach is to abandone smart-home integration and just go with standalone (I'm saying this only for vent). [community.home-assistant.io#12233/5](https://community.home-assistant.io/t/ecovent-anyone-else-have-one/12233/5) shows [AC Infinity AIRTAP T4](https://www.amazon.com/dp/B07H8R7X2M?ref=emc_s_m_5_i_atc) (4x12), a vent with embedded thermostat.

**Comment by 130s** [comment]
[Someone said (home-assistant.io)](https://community.home-assistant.io/t/multi-room-temp-inputs-to-one-thermostat/387147/18?u=130s) was successful on HASS, changing hvac set temperature based on multiple (not just one) sensor measurement.  Worth reviewing.

**Comment by 130s** [comment]
> SE forum ends up with "no Zigbee". Then I found [someone said](https://community.home-assistant.io/t/hvac-smart-vent-zoning-control-through-homeassistant-no-internet-required-but-recommended/440051/15) Keen works with Zigbee, so I'm asking for [a clarification](https://community.home-assistant.io/t/hvac-smart-vent-zoning-control-through-homeassistant-no-internet-required-but-recommended/440051/21).
> 
> Another approach is to abandone smart-home integration and just go with standalone (I'm saying this only for vent). [community.home-assistant.io#12233/5](https://community.home-assistant.io/t/ecovent-anyone-else-have-one/12233/5) shows [AC Infinity AIRTAP T4](https://www.amazon.com/dp/B07H8R7X2M?ref=emc_s_m_5_i_atc) (4x12), a vent with embedded thermostat.

Tried.

### Installation
Inside the targeted vent there was metal plates that prevented the device from sliding in.

![Image](https://github.com/user-attachments/assets/c8378510-d46c-4c5e-b2ab-a28ab4cd3d23)

I scraped the drywall in order for those metal plates to be pushed outward, which worked.

### Does it work for the purpose?

Maybe not. The ability I wanted is to block the air outflow when I want to, but with this device the air seems to always come out regardless the device being in action or not.

**Comment by 130s** [comment]
# Things to try
- [x] AC Infinity AIRTAP T4 -> https://github.com/kinu-garage/hut_10sqft/issues/1015#issuecomment-2843198477
- [ ] Figure out if Keen Smart vent can be integrated into HASS?
   - [ ] Custom HASS component: [aglehmann/home_assistant_ecovent](https://github.com/aglehmann/home_assistant_ecovent)
   - [ ] What do those people in [community.home-assistant.io#878717](https://community.home-assistant.io/t/keen-vent-cover-entity-no-longer-working-after-2025-4-2/878717) use in order to access the device?

**Comment by 130s** [comment]
Asked https://community.home-assistant.io/t/hvac-smart-vent-zoning-control-through-homeassistant-no-internet-required-but-recommended/440051/28

**Comment by 130s** [comment]
I figured out that the AC Infinity product does NOT block the wind flow when I want to. Instead, it blows out the air when I want to. With that, I now don't think it'd be helpful to be installed in the room that gets cold in summer.

I installed it in the kids room that is the most problematic regarding the room temperature.
![Image](https://github.com/user-attachments/assets/d1e9e757-ba8e-42f3-a878-4a768f91763f)

**Comment by 130s** [comment]
AC Infinity HASS custom https://community.home-assistant.io/t/ac-infinity-bluetooth-69-pro-controllers-successful/514068/24
