### ISSUE TITLE
Chromebook init setup; zork16 on Lenovo c13

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#1036]
Similar to https://github.com/kinu-garage/hut_10sqft/issues/890

- [ ] Host name to be not conflicting https://github.com/kinu-garage/hut_10sqft/issues/1035
- File systems
   - [x] Sync the files Linux-Emacs saves/modifies. https://github.com/kinu-garage/hut_10sqft/issues/962#issuecomment-1895512258
   - [x] Mount Google Drive folder on local file system. (After Recovery https://github.com/kinu-garage/hut_10sqft/issues/897#issuecomment-1726829950, G-Drive disappered from `Files`, let alone on the local file system). -> Delegated at https://github.com/kinu-garage/hut_10sqft/issues/898
- [ ] Apps
   - [ ]  Install Android apps that are used on another Chromebook(s) -> Seems to be done automatically.
   - [x] Minecraft installed on kids accounts.
   - [x] E-books downloaded on Kindle -> Chose NOT to install as of 20240112. Ref. https://github.com/kinu-garage/hut_10sqft/issues/882#issuecomment-1890415472
- Input
   - [x] Swap caps <--> `ctrl`, can be done in `Customize keyboard keys` 
   - [x] Behavior of switching tabs by `ALT + Tab` only switches forward to the adjacent tab, not the prev. tab. --> https://github.com/kinu-garage/hut_10sqft/issues/890#issuecomment-1712781875
   - [x] Trackpoint speed https://github.com/kinu-garage/hut_10sqft/issues/905
   - Japanese input
      - [x] Google Japanese input s/w Ref. https://github.com/kinu-garage/hut_10sqft/issues/517
      - [x] Google Jp input dictionary https://github.com/kinu-garage/hut_10sqft/issues/890#issuecomment-1725217879
      - [x] Switch EN<-->JP input by cmd, not GUI. https://github.com/kinu-garage/hut_10sqft/issues/892
- [ ] Linux mode
   - [x] Enabled Linux mode
   - [x] Dependency installed automatically -> Blocked by https://github.com/kinu-garage/hut_10sqft/issues/1037
   - [ ] Configs set automatically TBD (using the tool in hut_10sqft)
- Emacs
   - [x] Emacs on host  --> Delegated to Linux mode
   - [x] Japanese on Emacs? https://github.com/kinu-garage/hut_10sqft/issues/880
   - [ ] Apply my shared Emacs config TBD
- MOOC watch and learn on it
   - [ ] Headset connected
   - [ ] Stylus digitally connected
   - [ ] Stylus physically attached
- [ ] Check best practice about Chromebook https://www.makeuseof.com/tag/tips-first-time-chromebook-user/
- [ ] Else

**Comment by 130s** [comment]
Not having `mozc` on emacs blocked by https://github.com/kinu-garage/hut_10sqft/issues/797 is such an inconvenience and the bugfix for installing it via `suco` https://github.com/kinu-garage/hut_10sqft/pull/1245 is taking longer than I wanted. So manually installing it.

**Comment by 130s** [comment]
Other than the remaining tickets, I can't think of anything left undone.
