### ISSUE TITLE
Amazon Kindle's digital library to be shared among family

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#1043]
Explained in https://github.com/kinu-garage/hut_10sqft/issues/910#issuecomment-2134317516

CoS
- [x] Child can read the shared ebooks on their Fire OS https://github.com/kinu-garage/hut_10sqft/issues/1043#issuecomment-2476714483
- [ ] Child can read the shared ebooks on their ChromeOS https://github.com/kinu-garage/hut_10sqft/issues/1043#issuecomment-2476714483
- [x] Children can read the shared ebooks that are purchased through BOTH US and Japan accounts.
   - [x] amazon.co.jp https://github.com/kinu-garage/hut_10sqft/issues/1398#issuecomment-4356005719

**Comment by 130s** [comment]
Sharing among Amazon's `Household` members it is straightforward ([ref](https://www.amazon.com/gp/help/customer/display.html?nodeId=TMdeV7dcdzd4a4AajY)). I just shared a few contents with family members. Sharing can be done as a whole library, or per item per person, nice.

There's an issue though. Amazon's account is specific to a country. In the context of https://github.com/kinu-garage/hut_10sqft/issues/910#issuecomment-2134317516, contents of interest are bought under my non US country (Japan) account. For sharing b/w my own accounts, I've already managed to work around https://github.com/kinu-garage/hut_10sqft/issues/882. But I'm reluctant to ask my family members to do the same workaround...

**Comment by 130s** [comment]
I managed to set up a legit way to share an ebook with a minor in the family. Ended up buying a digital version on amazon.com, then shared it on my account on the Kindle e-reader app with the child's Kindle account so that the child can read the ebook on the Fire device with her account.

Detail:
### How I managed to have the particular ebook
1. Bought the [Ebook version was $6.99 (amazon.com)](https://www.amazon.com/Monsters-Percy-Jackson-Olympians-Book-ebook/dp/B00280LYHI/ref=tmm_kin_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.BwXR-Jrj8GzOJz-ODHVUPSbwuTBsF5RrvOAExlN8pu5SwjpLaB7Vj0_pFS_qyrVwi0kqV4DiJEIuToVeMp-lv0R1I6CZsMuuyCF9Z-tGdKmokC9x3nmA7MOH9UfLcKxe-xzAK-97V8LqjddrSuu5qIQluP19s194LlJkUg0696P38MraobMie6xjeVLp43SnzxFP1hZW-QNCtceCdQCLFW5GbBe9GbliOfhw-9VUnkY.q27GDjy7qnL7LBfaaU-lbyH4JnH2XGOCr8lL-6LNFoc&qid=1731594619&sr=8-1).
1. On my Kindle app on any device where I log on with my amazon.com account (which is a member of the family that is managed by the parents and children belong to without registering their emails), I manually share the particular e-content with the child's Kindle account.
1. On Fire device, switch to the child's account. On its desktop, search from the icon on right-top the ebook title then the ebook showed up in the search result. Already downloadable without buying again. Success.
### Attempted but NG:
- On Fire device there's an app [Free eBooks for Kindle](https://www.amazon.com/Neo-Nghia-Tran-eBooks-Kindle/dp/B00JWQM0IS/ref=sr_1_2?dib=eyJ2IjoiMSJ9.MeKhXcYTr_eUwz7a2nCns4EkyAvoszOcuXHDkO6d8jfb2O-TqDmUL7ZDn1aqr-S4JLuEFpgbDeO3N3zmHIRO13yCtNyvOH-yth74YuQWfX7RYCrjwf23R8B2h1lWNHfaVquV_HjsZ2p_sA-ewYKZPZAkjyDSgFEya1_a2z-ctf3iXFieREXwfZf7lb2OraViFdXRsuz48WczNt8n4m1NlEAhc_pI5eCKM4PVTIRHCpJsaLX4PDTjwFeOa_wZoebOVsaeI5IFOFlO59VjteVpsCuMBTa8kC6J0KVdXxiLCwE.ICa6FfOOLPlfAByiQWGHQVD9GxqkJRrvTBuuic9TUQ0&dib_tag=se&keywords=Ebooks+App&qid=1731596376&sr=8-2), [installed](https://groups.google.com/g/30y-130s/c/-EtfXBCCTEA) but couldn't find the particular ebook on that platform.
- ❓ On a child's ChromeOS device, I still don't know how I can share an ebook bought on Kindle e-reader, as I couldn't find how to have child log on on Kindle e-reader...I even created an account for the child on amazon.com, which didn't even ask the age btw, but then on Amazon Family I haven't found a way to associate with the child's account on amazon.com AND the child's account on Amazon Family (which is also used on Fire devices).

**Comment by 130s** [comment]
Related, an e-book I shared with the kids accounts, only on 2nd child's account it had not been appearing on this child's account on FireHD10 (saw it half an year ago, and today I did see the same).
Today I deleted an access on the content *1 to this child, and re-added an access, I did see the list of contents in "recent content"  list at the top of the desktop refreshed, but the very content still didn't appear. On search menu, seached the title then found it. Pressed "Download" and opened it w/o an issue.

*1...[The Dragons of Blueland (My Father's Dragon Series)](https://www.amazon.com/gp/product/B009Q6IN7Q/ref=kinw_myk_ro_title) by Ruth Stiles Gannett

**Comment by 130s** [comment]
> * [ ]  Child can read the shared ebooks on their ChromeOS [Amazon Kindle's digital library to be shared among family #1043 (comment)](https://github.com/kinu-garage/hut_10sqft/issues/1043#issuecomment-2476714483)

As of now that is hard / impossible to achieve as noted in https://github.com/kinu-garage/hut_10sqft/issues/1398

I'm good to call this done.
