### ISSUE TITLE
OS init tool; Initial setup on ChromeOS w/Linux mode is manually done

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#1045]
After initial handling of ChromeOS https://github.com/kinu-garage/hut_10sqft/pull/961, it still takes a long time to setup my ChromeOS for my usecases.

# CoS
- Functional reqs are met
   1. [x] Clone the repo by e.g. a single line of command
   2. [x] Config files to be obtained at the location Design-5 defines https://github.com/kinu-garage/hut_10sqft/issues/962#issuecomment-1895512258
   1. [x] Mount Google-Drive onto Linux image.
   1. [x] Directories made such as `~/link`.
   1. [x] Dependency auto installation not working https://github.com/kinu-garage/hut_10sqft/issues/1037
   3. [ ] Reports what was done and what was not done (and the reason for not being done).
   1. [ ] https://github.com/kinu-garage/hut_10sqft/issues/797
   1. [ ] Else?
- Operational reqs
   - [x] Can be executed multiple times on the same OS entity w/o causing  issues.
- Design detail reqs met
   - [x] No overhead in usage. Just do Python.
   - [ ] Modularized for re-use.
- Optionally address reported issues
   - [ ] Patch `convert`'s issue https://github.com/kinu-garage/hut_10sqft/issues/940#issuecomment-1837463108
   - [x] https://github.com/kinu-garage/hut_10sqft/issues/931

**Comment by 130s** [comment]
> * [ ]  Mount Google-Drive onto Linux image.

IDK if there's a way to do this programmatically from Linux. For now I just achieved this on `Files` app, right-click on the folder to mount on to Linux, enabled `Share with Linux` option.

**Comment by 130s** [comment]
Testing on a docker image `linuxserver/chromium:version-f9f075f0` from https://hub.docker.com/r/linuxserver/chromium

**Comment by 130s** [comment]
Btw, the choice of Docker images has settled down to the one with Ubuntu for now for the following reason per each:
- `linuxserver/chromium:version-f9f075f0`: On the attached `bash` console, with the following execution that I used a lot, `DISPLAY` error kept happening that made the console un-usable. 
   ```
   docker run -it --network host  --volume $PATH_LOCAL_WS:/cws/src  --volume /dev:/dev  $DOCKERIMG bash
   ```
   - Simpler `docker run -it $DOCKERIMG bash` didn't not cause the issue. I have not tried to identify which option caused the issue.
- `python:3.12.5-slim-bullseye`: Python's `sys.path` points to `/usr/local/lib`, which makes Python packages that are installed via `apt` not referenciable.
