### ISSUE TITLE
Chromebook init setup; c13-morph on Lenovo

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#1065]
Similar to https://github.com/kinu-garage/hut_10sqft/issues/1036

- [x] Host name to be not conflicting https://github.com/kinu-garage/hut_10sqft/issues/1035 --> Manually set for now.
- File systems
   - [ ] Sync the files Linux-Emacs saves/modifies. https://github.com/kinu-garage/hut_10sqft/issues/962#issuecomment-1895512258
   - [x] Mount Google Drive folder on local file system. (After Recovery https://github.com/kinu-garage/hut_10sqft/issues/897#issuecomment-1726829950, G-Drive disappered from `Files`, let alone on the local file system). -> Delegated at https://github.com/kinu-garage/hut_10sqft/issues/898
- [ ] Apps
   - [x]  Install Android apps that are used on another Chromebook(s) -> Seems to be done automatically.
   - [ ] Minecraft installed on kids accounts.
   - [ ] E-books downloaded on Kindle -> Debate whether or NOT to install as of 20240112. Ref. https://github.com/kinu-garage/hut_10sqft/issues/882#issuecomment-1890415472
- Input
   - [x] Swap caps <--> `ctrl`, can be done in `Customize keyboard keys` 
   - [ ] Behavior of switching tabs by `ALT + Tab` only switches forward to the adjacent tab, not the prev. tab. --> https://github.com/kinu-garage/hut_10sqft/issues/890#issuecomment-1712781875
   - [x] Trackpoint speed https://github.com/kinu-garage/hut_10sqft/issues/905
   - Japanese input
      - [ ] Google Japanese input s/w Ref. https://github.com/kinu-garage/hut_10sqft/issues/517
      - [ ] Google Jp input dictionary https://github.com/kinu-garage/hut_10sqft/issues/890#issuecomment-1725217879
      - [ ] Switch EN<-->JP input by cmd, not GUI. https://github.com/kinu-garage/hut_10sqft/issues/892
- [ ] Linux mode
   - [x] Enabled Linux mode
   - [x] Dependency installed automatically -> Blocked by https://github.com/kinu-garage/hut_10sqft/issues/1037
   - [ ] Configs set automatically TBD (using the tool in hut_10sqft)
- Emacs
   - [x] Emacs on host  --> Delegated to Linux mode
   - [x] Japanese on Emacs? https://github.com/kinu-garage/hut_10sqft/issues/880
   - [ ] Apply my shared Emacs config TBD
- MOOC watch and learn on it
   - [ ] Headset connected
   - [ ] Stylus digitally connected
   - [ ] Stylus physically attached
- [ ] Check best practice about Chromebook https://www.makeuseof.com/tag/tips-first-time-chromebook-user/

**Comment by 130s** [comment]
> c14-morph

But this device is Lenovo C13, not C14, isn't it?
