### ISSUE TITLE
ChromeOS: SUCO runtime issues after #1081

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#1082]
Tested on 130s-c13-morph. 

Not working on ChromeOS...

- [x] #1100
- [x] #1099 
- [ ] https://github.com/kinu-garage/hut_10sqft/issues/1102
- [x] Install cmd in the doc failed.
   ```
   $ export INITOS=/tmp/hut_10sqft_os-setup.py &&  \
     export VERSION=develop  \
     export HOST_NAME=130s-C13-Morph  \
     export OSTYPE=ChromeOS  \
     export USERID=gm130s  \
     sudo apt install -y curl python3  \
     curl --output $INITOS https://raw.githubusercontent.com/kinu-garage/hut_10sqft/$VERSION/hut_10sqft/src/hut_10sqft/init_setup.py && \
       chmod 755 $INITOS \
       $INITOS --hostname $HOST_NAME --os $OSTYPE --user_id $USERID
   -bash: export: `-y': not a valid identifier
   -bash: export: `--output': not a valid identifier
   -bash: export: `/tmp/hut_10sqft_os-setup.py': not a valid identifier
   -bash: export: `https://raw.githubusercontent.com/kinu-garage/hut_10sqft//hut_10sqft/src/hut_10sqft/init_setup.py': not a valid identifier
   ```
   - Exec cmd that worked:
      ```
      export INITOS=/tmp/hut_10sqft_os-setup.py &&    export VERSION=develop &&    export HOST_NAME=130s-C13-Morph &&    export OSTYPE=ChromeOS  &&  export USERID=gm130s &&  sudo apt install -y curl python3 &&    curl --output $INITOS https://raw.githubusercontent.com/kinu-garage/hut_10sqft/$VERSION/hut_10sqft/src/hut_10sqft/init_setup.py &&     chmod 755 $INITOS &&     $INITOS --hostname $HOST_NAME --os $OSTYPE --user_id $USERID
      ```
- [x] `~/.bashrc` not linked. https://github.com/kinu-garage/hut_10sqft/issues/796
- [x] SSH keys are not installed.
   ```
   $ ls -alth ~/.ssh
   ls: cannot access '/home/gm130s/.ssh': No such file or directory
   ```
- [ ] `link` dir duplicated w/o any good usage.
   ```
   $ ls -lath ~/link/link/
   total 4.0K
   drwxr-xr-x 1 gm130s gm130s 90 Sep  6 13:53 ..
   drwxr-xr-x 1 gm130s gm130s 22 Sep  6 13:53 .
   lrwxrwxrwx 1 gm130s gm130s 33 Sep  6 13:53 GoogleDrive -> /mnt/chromeos/GoogleDrive/MyDrive
   ```
- [x] `emacs-mozc`, `mozc-utils-gui` (error reads `mozc_tool` that the shortcut `mozc_conf_tool` references to) missing.
   ```
   File is missing: Cannot open load file, No such file or directory, mozc
   ```
- [x] `apt update` fails.
   ```
   $ sudo apt update
   Ign:1 https://apt.dockerproject.org/repo ubuntu- InRelease
   Hit:2 https://deb.debian.org/debian bookworm InRelease
   :
   Ign:1 https://apt.dockerproject.org/repo ubuntu- InRelease
   Err:1 https://apt.dockerproject.org/repo ubuntu- InRelease
   
   Something wicked happened resolving 'apt.dockerproject.org:https' (-5 - No address associated with hostname)
   Fetched 55.4 kB in 7s (7,666 B/s)  
   Reading package lists... Done  
   Building dependency tree... Done 
   Reading state information... Done 
   All packages are up to date.
   W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-/InRelease  Something wicked happened resolving 'apt.dockerproject.org:https' (-5 - No address associated with hostname)
   W: Some index files failed to download. They have been ignored, or old ones used instead. ```
- [x] `ack` in `bash` executable not found even though it's in package.xml.
- [x] `git fetch origin` fails.
   ```
   $ git fetch origin
   git@github.com: Permission denied (publickey).
   fatal: Could not read from remote repository.
   
   Please make sure you have the correct access rights
   and the repository exists.
   ```
    Update: I had to these things before `git` can access the remote:
    1. Generate ssh key by `ssh-keygen`.
    1. `chmod 700 id_rsa*`
    1. Register a pub key on to my account on github.com.
- [x] `rosdep` on `bash` not found.
   ```
   subprocess: About to execute the cmd: rosdep install --from-paths . --ignore-src -r -y
   output: , error: /bin/sh: 1: rosdep: not found, bash_return_code: 127
   ```
- [x] For unknown reason, `~/.config/hut_10sqft` already existed with the HEAD pointing to older commit than the version I intended to use.
   - This may or may not be the cause of `rosdep` not installing the pkgs as listed above.
- [x] It's c13-morph, not c14...
- [x] What if a backup file with the same name already exists? Does the existing backup get overwritten and lost?
- [x] FileNotFoundError: At '/root/.config/hut_10sqft', a local repo is expected to be present in order to continue. https://github.com/kinu-garage/hut_10sqft/issues/1094
- [x] https://github.com/kinu-garage/hut_10sqft/issues/1095
- [x] Setup finished without listing the captured issues. --> Actually it was happening but for some reason it was printed earlier than some of the `apt` outputs.
   <details><summary>Log</summary>
   
   ```
   :
   Unpacking xdotool (1:3.20160805.1-4) ...
   Setting up libxdo3:amd64 (1:3.20160805.1-4) ...
   Setting up xdotool (1:3.20160805.1-4) ...
   Processing triggers for man-db (2.9.4-2) ...
   Processing triggers for libc-bin (2.31-13+deb11u10) ...
   executing command [apt-get install -y ack]
   executing command [apt-get install -y apt-transport-https]
   executing command [apt-get install -y emacs]
   executing command [apt-get install -y gimp]
   executing command [apt-get install -y gnuplot]
   executing command [apt-get install -y gnuplot-x11]
   executing command [apt-get install -y meld]
   executing command [apt-get install -y mesa-utils]
   executing command [apt-get install -y meshlab]
   executing command [apt-get install -y ntp]
   executing command [apt-get install -y python3-empy]
   executing command [apt-get install -y python3-rocker]
   executing command [apt-get install -y python3-rosdep2]
   executing command [apt-get install -y python3-vcstool]
   executing command [apt-get install -y debtree]
   executing command [apt-get install -y nmap]
   executing command [apt-get install -y openssh-server]
   executing command [apt-get install -y texlive-fonts-recommended]
   executing command [apt-get install -y texlive-latex-base]
   executing command [apt-get install -y tree]
   executing command [apt-get install -y xdotool]
           Error: WARNING: ROS_PYTHON_VERSION is unset. Defaulting to 3
   ERROR: the following packages/stacks could not have their rosdep keys resolved
   to system dependencies (ROS distro is not set. Make sure `ROS_DISTRO` environment variable is set, or use `--rosdistro` option to specify the distro, e.g. `--rosdistro indigo`):
   hut_10sqft: Cannot locate rosdep definition for [rpl]
   Continuing to install resolvable dependencies...
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   E: Unable to locate package python3-rocker
   debconf: delaying package configuration, since apt-utils is not installed
   E: Unable to locate package python3-vcstool
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   ERROR: the following rosdeps failed to install
     apt: command [apt-get install -y python3-rocker] failed
     apt: command [apt-get install -y python3-vcstool] failed
     apt: Failed to detect successful installation of [python3-rocker]
     apt: Failed to detect successful installation of [python3-vcstool]
   Setup finished.
   ```
   </details>
- [x] `AttributeError: 'ChromeOsSetup' object has no attribute '_which_docker'`
   ```
   subprocess: About to execute the cmd: None $DEBIAN_FRONTEND
   subprocess: About to execute the cmd: None $DEBIAN_FRONTEND
   :
   output: , error: /bin/sh: 1: None: not found, bash_return_code: 127
   output: , error: /bin/sh: 1: None: not found, bash_return_code: 127
   output: , error: /bin/sh: 1: None: not found, bash_return_code: 127
   Traceback (most recent call last):
     File "/tmp/hut_10sqft_os-setup.py", line 1065, in <module>
       comp_setup.main()
     File "/tmp/hut_10sqft_os-setup.py", line 1053, in main
       _os_builder.run(_args,
     File "/tmp/hut_10sqft_os-setup.py", line 748, in run
       super().run(args, host_config, conf_repo_remote, conf_base_path)
     File "/tmp/hut_10sqft_os-setup.py", line 601, in run
       self.setup_docker(userid_os=self._os_user_id, skip=self._args_in.skip_setup_docker)
     File "/tmp/hut_10sqft_os-setup.py", line 782, in setup_docker
       OsUtil.subproc_bash(f'{self._which_docker} run hello-world && echo "docker seems to be installed successfully." || (echo "Something went wrong with docker installation."; RESULT=1', does_sudo=True)
                              ^^^^^^^^^^^^^^^^^^
   AttributeError: 'ChromeOsSetup' object has no attribute '_which_docker'. Did you mean: '_which_aptkey'?
   ```

## Carried over from https://github.com/kinu-garage/hut_10sqft/issues/1045
- Feature
   1. [ ] Reports as the end of execution what was done and what was not done (and the reason for not being done).
   1. [ ] https://github.com/kinu-garage/hut_10sqft/issues/797
- Design detail reqs met
   - [ ] Modularized for re-use.
- Optionally reported issues
   - [ ] Patch `convert`'s issue https://github.com/kinu-garage/hut_10sqft/issues/940#issuecomment-1837463108

**Comment by 130s** [comment]
- [ ] `~/.bashrc` not linked.

**Comment by 130s** [comment]
- [ ] SSH keys are not installed.
   ```
   $ ls -alth ~/.ssh
   ls: cannot access '/home/gm130s/.ssh': No such file or directory
   ```

**Comment by 130s** [comment]
Exec cmd that worked:
```
export INITOS=/tmp/hut_10sqft_os-setup.py &&    export VERSION=develop &&    export HOST_NAME=130s-C14-Morph &&    export OSTYPE=ChromeOS  &&  export USERID=gm130s &&  sudo apt install -y curl python3 &&    curl --output $INITOS https://raw.githubusercontent.com/kinu-garage/hut_10sqft/$VERSION/hut_10sqft/src/hut_10sqft/init_setup.py &&     chmod 755 $INITOS &&     $INITOS --hostname $HOST_NAME --os $OSTYPE --user_id $USERID
```

**Comment by 130s** [comment]
- [ ] `link` dir duplicated w/o any good usage.
   ```
   $ ls -lath ~/link/link/
   total 4.0K
   drwxr-xr-x 1 gm130s gm130s 90 Sep  6 13:53 ..
   drwxr-xr-x 1 gm130s gm130s 22 Sep  6 13:53 .
   lrwxrwxrwx 1 gm130s gm130s 33 Sep  6 13:53 GoogleDrive -> /mnt/chromeos/GoogleDrive/MyDrive
   ```

**Comment by 130s** [comment]
- [ ] `mozc` is missing.
   ```
   Warning (initialization): An error occurred while loading ‘/home/%USERID%/.emacs’:
   File is missing: Cannot open load file, No such file or directory, mozc
   ```

**Comment by 130s** [comment]
- [ ] `emacs-mozc`, `mozc_tool` (that the shortcut `mozc_conf_tool` references to) missing.
- [ ] `apt update` fails.
   ```
   $ sudo apt update
   Ign:1 https://apt.dockerproject.org/repo ubuntu- InRelease
   Hit:2 https://deb.debian.org/debian bookworm InRelease
   :
   Ign:1 https://apt.dockerproject.org/repo ubuntu- InRelease
   Err:1 https://apt.dockerproject.org/repo ubuntu- InRelease
   
   Something wicked happened resolving 'apt.dockerproject.org:https' (-5 - No address associated with hostname)
   Fetched 55.4 kB in 7s (7,666 B/s)  
   Reading package lists... Done  
   Building dependency tree... Done 
   Reading state information... Done 
   All packages are up to date.
   W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-/InRelease  Something wicked happened resolving 'apt.dockerproject.org:https' (-5 - No address associated with hostname)
   W: Some index files failed to download. They have been ignored, or old ones used instead. ```

**Comment by 130s** [comment]
- [ ] `ack` in `bash` executable not found even though it's in `package.xml`.

**Comment by 130s** [comment]
- [ ] `ack` in `bash` executable not found even though it's in package.xml.
- [ ] `git fetch origin` fails.
   ```
   $ git fetch origin
   git@github.com: Permission denied (publickey).
   fatal: Could not read from remote repository.
   
   Please make sure you have the correct access rights
   and the repository exists.
   ```

**Comment by 130s** [comment]
Created SSH key locally on c13-morph but `ssh-agent` keeps failing with it.
Also on this container I have been failing to reduce the creds file's visitbility...

```
$ ssh-add /home/gm130s/pcl/id_rsa
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0750 for '/home/gm130s/pcl/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
gm130s@penguin:~/pcl$ ls -ltha /home/gm130s/pcl/id_rsa
-rwxr-x--- 1 gm130s chronos-access 2.6K Sep  7 14:22 /home/gm130s/pcl/id_rsa
gm130s@penguin:~/pcl$ chmod 700 /home/gm130s/pcl/id_rsa.pub 
gm130s@penguin:~/pcl$ ls -ltha /home/gm130s/pcl/id_rsa
-rwxr-x--- 1 gm130s chronos-access 2.6K Sep  7 14:22 /home/gm130s/pcl/id_rsa
gm130s@penguin:~/pcl$ chmod go-x /home/gm130s/pcl/id_rsa.pub 
gm130s@penguin:~/pcl$ chmod go-x /home/gm130s/pcl/id_rsa
gm130s@penguin:~/pcl$ ls -ltha /home/gm130s/pcl/id_rsa
-rwxr-x--- 1 gm130s chronos-access 2.6K Sep  7 14:22 /home/gm130s/pcl/id_rsa
gm130s@penguin:~/pcl$ chgrp gm130s /home/gm130s/pcl/id_rsa
gm130s@penguin:~/pcl$ ls -ltha /home/gm130s/pcl/id_rsa
-rwxr-x--- 1 gm130s chronos-access 2.6K Sep  7 14:22 /home/gm130s/pcl/id_rsa
gm130s@penguin:~/pcl$ ssh-add /home/gm130s/pcl/id_rsa.pub
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0750 for '/home/gm130s/pcl/id_rsa.pub' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
```

**Comment by 130s** [comment]
> -  `git fetch origin` fails.

I had to these things before `git` can access the remote:
1. Generate ssh key by `ssh-keygen`.
1. `chmod 700 id_rsa*`
1. Register a pub key on to my account on github.com.

**Comment by 130s** [comment]
- [ ] `rosdep` cmd not found.
   ```
   $ rosdep
   -bash: rosdep: command not found
   ```
- [ ] For unknown reason, `~/.config/hut_10sqft` already existed with the HEAD pointing to older commit than the version I intended to use.
   - This may or may not be the cause of `rosdep` not installing the pkgs as listed above.

**Comment by 130s** [comment]
- [ ] It's c13-morph, not c14...

**Comment by 130s** [comment]
- [x] Still I don't see `.bashrc` is symlinked.
- [ ] Also saw weird issues that took me a while to resolve but once it's resolved I cannot repro.
   - `python3-git` didn't get installed via `apt` although subprocess_bash reported no issue. I kept running SUCO, then at some point the issue went away. Maybe right before that I might have `apt install -y python3-git` (or `purge`) manually but ID remember.
   - `ps` nor `w` didn't exist. But after a kind-of successful run of SUCO both were back available.

**Comment by 130s** [comment]
- [ ] What if a backup file with the same name already exists? Does the existing backup get overwritten and lost?

**Comment by 130s** [comment]
- [ ] Setup finished without listing the captured issues. --> Actually it was happening but for some reason it was printed earlier than some of the `apt` outputs.
   <details><summary>Log</summary>
   
   ```
   :
   Unpacking xdotool (1:3.20160805.1-4) ...
   Setting up libxdo3:amd64 (1:3.20160805.1-4) ...
   Setting up xdotool (1:3.20160805.1-4) ...
   Processing triggers for man-db (2.9.4-2) ...
   Processing triggers for libc-bin (2.31-13+deb11u10) ...
   executing command [apt-get install -y ack]
   executing command [apt-get install -y apt-transport-https]
   executing command [apt-get install -y emacs]
   executing command [apt-get install -y gimp]
   executing command [apt-get install -y gnuplot]
   executing command [apt-get install -y gnuplot-x11]
   executing command [apt-get install -y meld]
   executing command [apt-get install -y mesa-utils]
   executing command [apt-get install -y meshlab]
   executing command [apt-get install -y ntp]
   executing command [apt-get install -y python3-empy]
   executing command [apt-get install -y python3-rocker]
   executing command [apt-get install -y python3-rosdep2]
   executing command [apt-get install -y python3-vcstool]
   executing command [apt-get install -y debtree]
   executing command [apt-get install -y nmap]
   executing command [apt-get install -y openssh-server]
   executing command [apt-get install -y texlive-fonts-recommended]
   executing command [apt-get install -y texlive-latex-base]
   executing command [apt-get install -y tree]
   executing command [apt-get install -y xdotool]
           Error: WARNING: ROS_PYTHON_VERSION is unset. Defaulting to 3
   ERROR: the following packages/stacks could not have their rosdep keys resolved
   to system dependencies (ROS distro is not set. Make sure `ROS_DISTRO` environment variable is set, or use `--rosdistro` option to specify the distro, e.g. `--rosdistro indigo`):
   hut_10sqft: Cannot locate rosdep definition for [rpl]
   Continuing to install resolvable dependencies...
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   E: Unable to locate package python3-rocker
   debconf: delaying package configuration, since apt-utils is not installed
   E: Unable to locate package python3-vcstool
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   debconf: delaying package configuration, since apt-utils is not installed
   ERROR: the following rosdeps failed to install
     apt: command [apt-get install -y python3-rocker] failed
     apt: command [apt-get install -y python3-vcstool] failed
     apt: Failed to detect successful installation of [python3-rocker]
     apt: Failed to detect successful installation of [python3-vcstool]
   Setup finished.
   ```
   </details>

**Comment by 130s** [comment]
- [ ] `AttributeError: 'ChromeOsSetup' object has no attribute '_which_docker'`
   ```
   subprocess: About to execute the cmd: None $DEBIAN_FRONTEND
   subprocess: About to execute the cmd: None $DEBIAN_FRONTEND
   :
   output: , error: /bin/sh: 1: None: not found, bash_return_code: 127
   output: , error: /bin/sh: 1: None: not found, bash_return_code: 127
   output: , error: /bin/sh: 1: None: not found, bash_return_code: 127
   Traceback (most recent call last):
     File "/tmp/hut_10sqft_os-setup.py", line 1065, in <module>
       comp_setup.main()
     File "/tmp/hut_10sqft_os-setup.py", line 1053, in main
       _os_builder.run(_args,
     File "/tmp/hut_10sqft_os-setup.py", line 748, in run
       super().run(args, host_config, conf_repo_remote, conf_base_path)
     File "/tmp/hut_10sqft_os-setup.py", line 601, in run
       self.setup_docker(userid_os=self._os_user_id, skip=self._args_in.skip_setup_docker)
     File "/tmp/hut_10sqft_os-setup.py", line 782, in setup_docker
       OsUtil.subproc_bash(f'{self._which_docker} run hello-world && echo "docker seems to be installed successfully." || (echo "Something went wrong with docker installation."; RESULT=1', does_sudo=True)
                              ^^^^^^^^^^^^^^^^^^
   AttributeError: 'ChromeOsSetup' object has no attribute '_which_docker'. Did you mean: '_which_aptkey'?
   ```

**Comment by 130s** [comment]
- [ ] `apt` packages that are hosted on ros.org apt source aren't installed, which is a known issue.

**Comment by 130s** [comment]
- [ ] `pip` executabel not available.
   ```
   List of pip pkgs TO BE installed: ['rosdep']
   /usr/bin/python3: No module named pip
      Traceback (most recent call last):
        File "/tmp/hut_10sqft_os-setup.py", line 1066, in <module>
          comp_setup.main()
        File "/tmp/hut_10sqft_os-setup.py", line 1054, in main
          _os_builder.run(_args,
        File "/tmp/hut_10sqft_os-setup.py", line 749, in run
          super().run(args, host_config, conf_repo_remote, conf_base_path)
        File "/tmp/hut_10sqft_os-setup.py", line 616, in run
          self.install_deps_adhoc(deb_pkgs=[], pip_pkgs=["rosdep"])
        File "/tmp/hut_10sqft_os-setup.py", line 715, in install_deps_adhoc
          OsUtil.install_pip_adhoc(pip_pkgs)
        File "/tmp/hut_10sqft_os-setup.py", line 168, in install_pip_adhoc
          subprocess.check_call([sys.executable, '-m', 'pip', 'install', *pip_pkgs])
        File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
   subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', 'rosdep']' returned non-zero exit status 1.
   ```
