### ISSUE TITLE
2021 Christmas lights automation

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#401]
Todos
1. Razberry on RPi2
   1. [x] z-wave server with Razberry (on RaspberryPi2) https://github.com/130s/hut_10sqft/issues/338 -> Turned out not working as z-way poor performance.
   1. [x] <s>Hook up power strap to z-wave server. May or may not be https://github.com/130s/hut_10sqft/issues/187</s> --> Not necessarily related.
   1. [x] Lab test: Scheduling feature from z-wave controller. -> Turned out not working as z-way poor performance.
1. Razberry on RPi2 again?
   1. [x] Redo; z-wave server with Razberry (on RaspberryPi2) using RazBerry https://github.com/130s/hut_10sqft/issues/402
1. z-wave controller on RPi3
   1. [x] Decide OS and z-wave controller https://github.com/130s/hut_10sqft/issues/418
   1. [x] Lab test: Setup z-wave controller. Will try to follow advanced installation of zwave js https://github.com/130s/hut_10sqft/issues/610
   2. [x] Lab: Scheduling feature from z-wave controller works.
   2. [x] Home automation framework, aka "Hub" in z-wave terminology. https://github.com/130s/hut_10sqft/issues/552
   1. [x] Lab test: Integration with home automation framework.
1. [x] Idea. What to present https://github.com/130s/hut_10sqft/issues/625
1. [x] Deploy on the real environment.
1. [x] (Option) Hook up firefly light https://github.com/130s/hut_10sqft/issues/94
1. [x] Scheduling feature via home automation. If that works, that's preferable and the scheduling via Z-Wave can be disabled.
1. [x] (Very optional) Scheduling feature via home automation tool's Android app.
1. [ ] Web interface integration https://github.com/130s/hut_10sqft/issues/626

**Comment by 130s** [comment]
Todos
1. [ ] z-wave server with Razberry (on RaspberryPi2) https://github.com/130s/hut_10sqft/issues/338
1. [ ] Hook up power strap to z-wave server. May or may not be https://github.com/130s/hut_10sqft/issues/187

**Comment by 130s** [comment]
> - [ ]  Scheduling feature from z-wave controller.

Confirmed it worked with simple enough instruction from http://noo-rpi2.local:8083/smarthome/#/schedules

**Comment by 130s** [comment]
> > * [ ]   Scheduling feature from z-wave controller.
> 
> Confirmed it worked with simple enough instruction from http://noo-rpi2.local:8083/smarthome/#/schedules

However, that was in my lab. Once I moved the Z-Wave device to the room where christmas light is, which is 5+ meters away with multiple walls, Z-Wave controller seems to have lost the wireless connection.

**Comment by 130s** [comment]
I setup another Z-Wave, kind of like in-between so hopefully mesh network would establish, but so far the one at the far hasn't been detected. There were moments where control panel showed it somehow, which indicates network is spotty but not impossible though.

**Comment by 130s** [comment]
[hubitat.com](https://docs.hubitat.com/index.php?title=How_to_Build_a_Solid_Z-Wave_Mesh) gives a good explanation and tip about inclusion, exclusion and other practices for maintaining a good z-wave network.

So I triggered removal of the device from Z-Way web, but the popup never completed. In the meantime, I long-pressed the button on the device to initiate the exclusion on the device side (as instructed so in its manual).

Exclusion of the device that moved away to further location has never completed. 

Decided to do factory reset the z-way server.
```
$ sudo apt-get purge z-way-full && sudo apt-get autoremove
$ sudo apt-get install z-way-full
```

Looks like config is still not removed as I can see devices that I included before the purge.

Turned out some configs are saved in `/opt/z-way-server/`.
```
$ sudo rm -fr /opt/z-way-server/ && sudo apt-get purge z-way-full
```
(Purge should happen first. I'm just keeping the order I did for the record)

Then, web i/f started saying:
> An unexpected error occurred during loading data. Try to reload the page.
> Please check your ethernet connection and the power supply of your gateway. Try to reload the page after some minutes to get back to the Smart Home UI, if it doesn't will be triggered automatically

After repeating purging-reinstalling z-way-server multiple times, web server doesn't even start. I might have removed something that happened at the very initial installation of z-way server.

**Comment by 130s** [comment]
Running install step from the section from https://z-wave.me/z-way/download-z-way/
```
$ wget -q -O - https://storage.z-wave.me/RaspbianInstall | sudo bash
Ign:1 http://repos.azulsystems.com/debian stable InRelease
Hit:2 http://repos.azulsystems.com/debian stable Release                                      
Get:3 http://archive.raspberrypi.org/debian stretch InRelease [25.4 kB]                       
Hit:4 http://raspbian.raspberrypi.org/raspbian stretch InRelease                     
Ign:6 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Get:7 https://dl.bintray.com/openhab/apt-repo2 stable Release [6,051 B]
Hit:7 https://dl.bintray.com/openhab/apt-repo2 stable Release
Hit:8 https://repo.z-wave.me/z-way/raspbian stretch InRelease
Fetched 25.4 kB in 4s (5,290 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.4.9).
dirmngr is already the newest version (2.1.18-8~deb9u4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Executing: /tmp/apt-key-gpghome.9Mg42a8m9F/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0x7E148E3C
gpg: key 2222290F7E148E3C: "Z-Wave.Me <info@z-wave.me>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Ign:1 http://repos.azulsystems.com/debian stable InRelease
Hit:2 http://repos.azulsystems.com/debian stable Release                                      
Get:3 http://archive.raspberrypi.org/debian stretch InRelease [25.4 kB]                       
Hit:4 http://raspbian.raspberrypi.org/raspbian stretch InRelease                     
Ign:5 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Get:6 https://dl.bintray.com/openhab/apt-repo2 stable Release [6,051 B]
Hit:6 https://dl.bintray.com/openhab/apt-repo2 stable Release
Hit:8 https://repo.z-wave.me/z-way/raspbian stretch InRelease
Fetched 25.4 kB in 4s (5,398 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/822 B of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 62000 files and directories currently installed.)
Preparing to unpack .../z-way-full_1.0-latest-version_all.deb ...
Unpacking z-way-full (1.0-latest-version) over (1.0-latest-version) ...
Setting up z-way-full (1.0-latest-version) ...
Updating FireMotD available updates count ... 2019-12-15 03:54:20,199: FireMotD: Error: Template folder doesn't exist. Upgrading from an older version? Please run make again or run the install function "FireMotD -I -v".
```
Hopefully `FireMotD: Error` is for openHAB and has nothing to do with Z-Way so ignoring https://community.openhab.org/t/solved-openhab-2-3-0-1-stable-no-firemotd-exportfile-detected/47992

But still not sure.

**Comment by 130s** [comment]
> Hopefully FireMotD: Error is for openHAB and has nothing to do with Z-Way so ignoring https://community.openhab.org/t/solved-openhab-2-3-0-1-stable-no-firemotd-exportfile-detected/47992

The same error occurred during the very first z-way installation https://github.com/130s/hut_10sqft/issues/338#issuecomment-565761857, so this is not likely an issue.

Still, I still see the web server http://nooo-rpi2:8083/ `Unable to connect`.

**Comment by 130s** [comment]
Re-ran install script then I might have started seeing a new error.
```
Preparing to unpack .../apt/archives/zbw_1.2_all.deb ...
cat: /etc/zbw/passwd: No such file or directory
Didn't find passwd file
dpkg: error processing archive /var/cache/apt/archives/zbw_1.2_all.deb (--unpack):
```
More log.
```
nnooo@nooo-rpi2:~ $ sudo apt-get purge z-way-server z-way-full && apt-get autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 webif : Depends: z-way-server but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
nnooo@nooo-rpi2:~ $ sudo apt-get --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  zbw
The following NEW packages will be installed:
  zbw
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
12 not fully installed or removed.
Need to get 0 B/4,740 B of archives.
After this operation, 36.9 kB of additional disk space will be used.
Do you want to continue? [Y/n]
(Reading database ... 62039 files and directories currently installed.)
Preparing to unpack .../apt/archives/zbw_1.2_all.deb ...
cat: /etc/zbw/passwd: No such file or directory
Didn't find passwd file
dpkg: error processing archive /var/cache/apt/archives/zbw_1.2_all.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/zbw_1.2_all.deb
Updating FireMotD available updates count ... 2019-12-25 09:21:54,622: FireMotD: Error: Template folder doesn't exist. Upgrading from an older version? Please run make again or run the install function "FireMotD -I -v".

E: Sub-process /usr/bin/dpkg returned an error code (1)
```

```
Dec 25 09:17:02 nooo-rpi2 CRON[17305]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 25 09:17:02 nooo-rpi2 CRON[17309]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Dec 25 09:17:02 nooo-rpi2 CRON[17305]: pam_unix(cron:session): session closed for user root
Dec 25 09:18:40 nooo-rpi2 systemd-logind[293]: Removed session c1.
-- Subject: Session c1 has been terminated
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A session with the ID c1 has been terminated.
Dec 25 09:19:25 nooo-rpi2 sudo[17657]:    nnooo : TTY=pts/2 ; PWD=/home/nnooo ; USER=root ; COMMAND=/bin/systemctl status zbw_connect.service
Dec 25 09:19:25 nooo-rpi2 sudo[17657]: pam_unix(sudo:session): session opened for user root by nnooo(uid=0)
Dec 25 09:19:25 nooo-rpi2 sudo[17657]: pam_unix(sudo:session): session closed for user root
Dec 25 09:19:47 nooo-rpi2 sudo[17725]:    nnooo : TTY=pts/2 ; PWD=/home/nnooo ; USER=root ; COMMAND=/usr/sbin/service zbw_connect start
Dec 25 09:19:47 nooo-rpi2 sudo[17725]: pam_unix(sudo:session): session opened for user root by nnooo(uid=0)
Dec 25 09:19:48 nooo-rpi2 systemd[1]: Starting LSB: zbw_connect...
-- Subject: Unit zbw_connect.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit zbw_connect.service has begun starting up.
Dec 25 09:19:48 nooo-rpi2 zbw_connect[17752]: cat: /etc/zbw/passwd: No such file or directory
Dec 25 09:19:48 nooo-rpi2 zbw_connect[17752]: Didn't find passwd file
Dec 25 09:19:48 nooo-rpi2 systemd[1]: zbw_connect.service: Control process exited, code=exited status=1
Dec 25 09:19:48 nooo-rpi2 systemd[1]: Failed to start LSB: zbw_connect.
-- Subject: Unit zbw_connect.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit zbw_connect.service has failed.
--
-- The result is failed.
Dec 25 09:19:48 nooo-rpi2 systemd[1]: zbw_connect.service: Unit entered failed state.
Dec 25 09:19:48 nooo-rpi2 systemd[1]: zbw_connect.service: Failed with result 'exit-code'.
Dec 25 09:19:48 nooo-rpi2 sudo[17725]: pam_unix(sudo:session): session closed for user root
```

**Comment by 130s** [comment]
z-way server setup issue https://github.com/130s/hut_10sqft/issues/401#issuecomment-568917689 is moved back to https://github.com/130s/hut_10sqft/issues/338#issuecomment-568918469

**Comment by 130s** [comment]
Not sure where else I posted but for the record, I've spent tons of time in getting z-way software (along with `RazBerry`, the hardware) work but I concluded z-way is unsable for me. In  https://github.com/130s/hut_10sqft/issues/402 another server/driver software will be evaluated.

**Comment by 130s** [comment]
Updated OP

Todos
1. Razberry on RPi2
   1. [x] z-wave server with Razberry (on RaspberryPi2) https://github.com/130s/hut_10sqft/issues/338 -> Turned out not working as z-way poor performance.
   1. [x] <s>Hook up power strap to z-wave server. May or may not be https://github.com/130s/hut_10sqft/issues/187</s> --> Not necessarily related.
   1. [x] Lab test: Scheduling feature from z-wave controller. -> Turned out not working as z-way poor performance.
1. Razberry on RPi2 again?
   1. [x] Redo; z-wave server with Razberry (on RaspberryPi2) using RazBerry https://github.com/130s/hut_10sqft/issues/402
1. z-wave controller on RPi3
   1. [ ] Decide OS and z-wave controller https://github.com/130s/hut_10sqft/issues/418
   1. [ ] Lab test: Scheduling feature from z-wave controller works.
   1. [ ] Lab test: Integration with home automation framework.
1. [ ] Deploy on the real environment.
1. [ ] (Option) Hook up firefly light https://github.com/130s/hut_10sqft/issues/94
1. [ ] Scheduling feature via home automation. If that works, that's preferable and the scheduling via Z-Wave can be disabled.
1. [ ] (Very optional) Scheduling feature via home automation tool's Android app.

**Comment by 130s** [comment]
> -  Decide OS and z-wave controller #418

OS independent I guess as I chose a proprietary product that must come with onboard OS.

**Comment by 130s** [comment]
> 3. z-wave controller on RPi3
> :
>    - Lab: Scheduling feature from z-wave controller works.

Via HoA though (i.e. not Z-wave gateway itself), I was able to easily make an automation rule to turn off a z-wave switch off. I did so in 10 mins w/o looking up any instructions.

**Comment by 130s** [comment]
Done this year.
