### ISSUE TITLE
Not easy to notice when a door (even with a contact sensor) is left open

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#572]
# Potential resolution
- If ring.com can be configured to push notification for un-closed doors

Req (subject to change
- Notify when a door is left for certain period.
   - Notify on cellphone.
   - Notify by sound in the house (this shouldn't require cellphone).
- Period can be configured per each door/contact sensor.

CoS
- Sensor installed.
   - [x] 1st fridge
   - [x] 2nd fridge
   - [x] Closets
- [ ] Solution (to get notified when a door left open for certain period) decided.
- Notification implemented at non-security entry (doors that don't trigger alarming events):
   - [x] 1st fridge (previously tracked in https://github.com/130s/hut_10sqft/issues/609) -> https://github.com/kinu-garage/hut_10sqft/issues/863
   - [x] 2nd fridge (previously tracked in https://github.com/130s/hut_10sqft/issues/544) -> https://github.com/kinu-garage/hut_10sqft/issues/863
   - [x] Closets
   - [x] https://github.com/kinu-garage/30y-130s_life/issues/1151
- Notify for security-entry:
   - [x] Garage 1 & 2 https://github.com/kinu-garage/hut_10sqft/issues/856

**Comment by 130s** [comment]
Apparently there's a [feature request (ring.com)](https://community.ring.com/t/open-sensor-notification/10416/46) that's stale..

**Comment by 130s** [comment]
I'm finding `Home Assistant` useful and easy to maintain. Will consider switching non-critical features to it and use ring.com for only minimum 1) critical security features, 2) features ring excels (motion sensing cameras etc.)

ring.com is a very reasonable option regarding routine cost. Still, lack of response for high demand features like this is frustrating. With these I'll try taking the happy medium.

**Comment by 130s** [comment]
I was able to easily connect the Ring's contact sensor to HoA https://community.home-assistant.io/t/ring-z-wave-plus-door-window-contact-sensor-does-this-work-with-ha/115927/18. Next is to experiment notification rules via HoA when the door is left open.

Btw Ring's Z-wave contact sensor gen2 https://www.amazon.com/Ring-Alarm-Contact-Sensor/dp/B07ZB2QLC2 is $20, very economical.

**Comment by 130s** [comment]
I'd say not being able to make changes easily on OS level would block many tasks like this, hence this ticket is blocked by https://github.com/130s/hut_10sqft/issues/644

**Comment by 130s** [comment]
> -  Solution (to get notified when a door left open for certain period) decided.

Developed in https://github.com/kinu-garage/hut_10sqft/issues/856. Can be applied to other devices/entities.

**Comment by 130s** [comment]
> - Sensor installed.
>    * [x]  1st fridge
>    * [x]  2nd fridge

Both of them were not in the HASS' Z-Wave network for awhile and also they were removed for awhile. I'll re-include in Z-Wave network.

**Comment by 130s** [comment]
> - Sensor installed.
>    * [x]  1st fridge
>    * [x]  2nd fridge

Both of them were not in the HASS' Z-Wave network for awhile and also they were removed for awhile. I'll re-include in Z-Wave network.

1. Factory reset. https://support.ring.com/hc/en-us/articles/360042311972-Troubleshooting-Your-Contact-Sensor-2nd-Generation-
1. Included to z-wavejs https://community.home-assistant.io/t/ring-z-wave-plus-door-window-contact-sensor-does-this-work-with-ha/115927/17
   - I'm surprised a bit to find out that there doesn't seem to be better way invented in the past few years regarding the way to include Ring Contact Sensor gen2 to Z-Wavejs

**Comment by 130s** [comment]
Done except for https://github.com/kinu-garage/30y-130s_life/issues/1151, which will be closed separately.
