### ISSUE TITLE
Epic: Kick start learning ROS2

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#599]
At some point I have to learn ROS2.

1. Complete basic tutorial? https://docs.ros.org/en/foxy/Tutorials.html
   - [x] CLI
   - [x] Client libraries
      - [x] `rclpy`'s asynchronousity https://docs.ros.org/en/humble/How-To-Guides/Sync-Vs-Async.html
   - [x] ROS1 bridge
   - [ ] Intermediate
      - [ ] `Component` https://docs.ros.org/en/humble/Concepts/About-Composition.html
   - [ ] Advanced
   - [ ] Demos
   - [ ] Misc
1. [ ] To be able to run Turtlebot2 with ROS2? https://answers.ros.org/question/364448/porting-turtlebot2-to-ros2/ -> https://github.com/kinu-garage/hut_10sqft/issues/786
1. Else?

**Comment by 130s** [comment]
<details><summary># Configure env</summary>

```
export DIMG=osrf/ros:humble-desktop-jammy
docker run -it --network host --privileged $DIMG bash
```
```
source /opt/ros/humble/setup.bash
```
```
export DIMG=osrf/ros:humble-desktop-jammy
docker run -it --network host --privileged --name=ros2_tc2 $DIMG bash
```
```
$ docker exec -it dreamy_heisenberg bash

root@130s-p50:/# source /opt/ros/humble/setup.bash
ros2 run demo_nodes_py listener
[INFO] [1676431617.438015030] [listener]: I heard: [Hello World: 302]
[INFO] [1676431618.397089459] [listener]: I heard: [Hello World: 303]
[INFO] [1676431619.397097659] [listener]: I heard: [Hello World: 304]
```

## Trying ros1-ros2 bridge

For ros1 easiness I'm moving back to 20.04.

```
$ export DIMG=ros:noetic-perception-focal
$ docker run -it --network host --privileged $DIMG bash

echo "On Docker container"
locale  # check for UTF-8
apt update && sudo apt install locales
locale-gen en_US en_US.UTF-8
update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8
locale  # verify settings

apt install software-properties-common && add-apt-repository universe

apt update && sudo apt install curl && curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
apt update && apt upgrade
apt install ros-foxy-desktop python3-argcomplete
apt install ros-dev-tools

echo "term-1"
source /opt/ros/foxy/setup.bash
ros2 run demo_nodes_cpp talker

echo "term-2"
source /opt/ros/foxy/setup.bash
ros2 run demo_nodes_py listener
```
ROS2 Foxy on 20.04 is ready.

```
export ROS1_INSTALL_PATH=/opt/ros/noetic/
source ${ROS1_INSTALL_PATH}/setup.bash
roscore
```
Start bridge
```
# export ROS1_INSTALL_PATH=/opt/ros/noetic/
# export ROS2_INSTALL_PATH=/opt/ros/foxy/

# Shell B (ROS 1 + ROS 2):
# Source ROS 1 first:
source ${ROS1_INSTALL_PATH}/setup.bash
# Or, on OSX, something like:
# . ~/ros_catkin_ws/install_isolated/setup.bash
# Source ROS 2 next:
source ${ROS2_INSTALL_PATH}/setup.bash
# For example:
# . /opt/ros/dashing/setup.bash
export ROS_MASTER_URI=http://localhost:11311
ros2 run ros1_bridge dynamic_bridge
```
I had to install bridge:
```
apt install ros-foxy-ros1-bridge
```
```
rostopic pub /topic_test_ros1_bridge std_msgs/String hello
```
```
export ROS2_INSTALL_PATH=/opt/ros/foxy/
source ${ROS2_INSTALL_PATH}/setup.bash
ros2 run demo_nodes_cpp listener
```
</details>

<details><summary># "Using turtlesim and rqt"</summary>

https://docs.ros.org/en/humble/Tutorials/Beginner-CLI-Tools/Introducing-Turtlesim/Introducing-Turtlesim.html
```
apt update && apt install ros-humble-turtlesim
```
`rqt` spawns from a Docker container.
```
$ export DIMG=osrf/ros:humble-desktop-jammy
$ rocker --x11 --user $DIMG rqt
```
Now turtlesim
```
rocker --x11 --user $DIMG ros2 run turtlesim turtlesim_node
```

</details>

**Comment by 130s** [comment]
https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Creating-Your-First-ROS2-Package.html

```
ros2 pkg create --build-type ament_cmake onyanko_gonpoko
ros2 pkg create --build-type ament_python onyanko_gonpy
```
Interesting, in the auto-generated Python pkg I don't see `CMakeLists.txt` any more. `my_node` python file in the source folder doesn't have executable right enabled, but in install space it does. I haven't figured out where this installation rule is defined. Maybe because it's set as an entry point (for the entire Py pkg) in `setup.py`?

```
# more setup.py
from setuptools import setup

package_name = 'onyanko_gonpy'

setup(
    name=package_name,
    version='0.0.0',
    packages=[package_name],
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='130s',
    maintainer_email='130s@todo.todo',
    description='TODO: Package description',
    license='Apache License 2.0',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'my_node = onyanko_gonpy.my_node:main'
        ],
    },
)
```

Maybe this is it https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Py-Publisher-And-Subscriber.html#check-setup-cfg
> This is simply telling setuptools to put your executables in `lib`, because `ros2 run` will look for them there.

**Comment by 130s** [comment]
Event handling capability in launch https://docs.ros.org/en/humble/Tutorials/Intermediate/Launch/Using-Event-Handlers.html is nice, there are usecases I'd want this in the past. It makes launch's domain even more blur (Although `.launch` files are just a config file passed to an executable `roslaunch`, many people might have taken it a special file, almost as an executable or a module).

**Comment by 130s** [comment]
Getting comfortable enough, I mean I haven't run into major difference points yet though e.g. com layer, I should be able to learn as I go.
