### ISSUE TITLE
Air quality to be integrated into home automation

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#677]
CoS
- Home Automation to utilize outside air quality measurement.
   - [x] HASS receives outside air quality measurement.
   - [ ] HASS controls air filters based on measurement.
- [ ] Home Automation to utilize inside air quality measurement.
   - [x] Sensor choice https://github.com/130s/hut_10sqft/issues/567
   - [x] HASS receives inside air quality measurement.
   - [ ] HASS controls air filters based on measurement.

**Comment by 130s** [comment]
> - Home Automation to utilize outside air quality measurement.

Using https://www.home-assistant.io/integrations/airvisual/ I can see some of the measurement of AirVisual on my HoA's Lovelace.

<details><summary>AirVisual api key gen</summary>

Fri May 27 2022 01:58:27 GMT-04:00
</details>

**Comment by 130s** [comment]
- [Serial Particulate Matter (home-assistant.io)](https://www.home-assistant.io/integrations/serial_pm/) only lists [plantower,pms5003](https://www.amazon.com/DEVMO-Digital-Particle-Concentration-PMS5003/dp/B07S5YX84W/ref=sr_1_3?crid=1IYA0EZW9F751&keywords=pms3003&qid=1653632769&s=industrial&sprefix=pms3003%2Cindustrial%2C63&sr=1-3&th=1) and other plantower products, plus a few other options. Serial connection means one sensor requires one computer e.g. Arduino (these days??), RPi, which may be overkill/over maintenance for me. [HoA integration looks good](https://community.home-assistant.io/t/air-quality-sensor-hardware-advice/273106/8) though.
- [PurpleAir](https://community.home-assistant.io/t/air-quality-sensor-hardware-advice/273106/12): [Lengthy thread about integration (home-assistant.io)](https://community.home-assistant.io/t/purpleair-air-quality-sensor/146588/150)

**Comment by 130s** [comment]
Both In/Outdoor measurements are now received by our HASS.

**Comment by 130s** [comment]
https://github.com/130s/hut_10sqft/issues/567#issuecomment-1147155054 reads HASS added the device once it's connected to the Internet/LAN, but that's not the case after migrating to a new HASS instance https://github.com/130s/hut_10sqft/issues/644.

**Comment by 130s** [comment]
> https://github.com/130s/hut_10sqft/issues/567#issuecomment-1147155054 reads HASS added the device once it's connected to the Internet/LAN, but that's not the case after migrating to a new HASS instance https://github.com/130s/hut_10sqft/issues/644.

To add a measurement from the device to HASS, 
1. Click `Add my integration` at https://www.home-assistant.io/integrations/airvisual/
1. You may be presented multiple options incl. "api key w/lat- and longitude", "geolocation name". Choose `AirVisual Pro/Node` or simular. That seems to be the name of the hardware I have.
1. Figure out somehow the IP address of your AirVisual device in my LAN. I looked into the DHCP server's log to find it.

Done.

**Comment by 130s** [comment]
> -  HASS controls air filters based on measurement.

I don't feel the necessity of this for now. Regularly having the air filter on for set amount of time is fine esp. some of our kids are having perpetually respiratory problems.
