### ISSUE TITLE
SUCO: Setting up `mozc` is manually done and cumbersome, error-prone

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#797]
CoS
- [x] Likely blocked by https://github.com/kinu-garage/hut_10sqft/issues/1037 -> No that one is for `chromeos` thus not blocking this.
- [x] Necessary pkgs are installed by SUCO. -> Done by https://github.com/kinu-garage/hut_10sqft/pull/1245
- [ ] Setup is automated.
   - [ ] Importing a dictionary
   - [ ] Choosing custom punctuation

**Comment by 130s** [comment]
Manual steps
1. Enabling Japanese as an option
   1. On setting GUI, Language support, add Japanese
   1.- Adding language on GNOME window manager
1. Enabling shortcut that enables language switch
   1. Run `gnome-control-center`
   1. `Keyboard -> Keyboard shortcuts -> View and Customize Shortcuts -> Typing -> Switch to next input source`
1. Set dictionary manually...
   - Btw hope it automatically synchs with the local file...Filed https://github.com/google/mozc/issues/426
1. Emacs keybind seems to be enabled already.

**Comment by 130s** [comment]
On p16s I found `emacs-mozc`, `emacs-mozc-bin` were NOT installed. Interestingly, after manually installing them via `apt`, a warning Emacs was showing upon its startup, which mentioned something about `~/.emacs`, is gone. To be addressed in https://github.com/kinu-garage/hut_10sqft/issues/797

**Comment by 130s** [comment]
There's no plan to prioritize this for now.

**Comment by 130s** [comment]
On p16s-2 on 24.04,
1. `apt install`ed `emacs-mozc, mozc-utils`.
1. `mozc_conf_tool` then imported a dict file.

This enabled mozc on Emacs.

**Comment by 130s** [comment]
On `opFyde-rpi5` https://github.com/kinu-garage/hut_10sqft/issues/1233, after a successful run of SUCO, opening Emacs shows this.

```
Warning (initialization): An error occurred while loading ‘/home/gm130s/.emacs’:

File is missing: Cannot open load file, No such file or directory, mozc

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace. Disable showing Disable logging
```

**Comment by 130s** [comment]
After a SUCO ran on opFyde-rpi5, `mozc` didn't get installed.

```
:
Installing by apt: ['aptitude', 'colorized-logs', 'dconf-editor', 'evince', 'flameshot', 'gnome-screenshots', 'gnome-tweaks', 'emacs-mozc, emacs-mozc-bin, ibus-mozc, mozc-utils, mozc-server', 'googleearth-package', 'gtk-recordmydesktop', 'ibus', 'ibus-el', 'indicator-multiload', 'libavahi-compat-libdnssd1', 'pdftk-java', 'pidgin', 'psensor', 'python-software-properties', 'ptex-base', 'ptex-bin', 'sysinfo', 'synaptic', 'xbindkeys', 'xsel', 'whois']
subprocess: About to execute the cmd: /usr/bin/apt update   bash_return_code=0, output="Ign:1 https://apt.dockerproject.org/repo ubuntu-bookworm InRelease\nHit:2 https://deb.debian.org/debian bookworm InRelease\nHit:3 https://deb.debian.org/debian bookworm-updates InRelease\nHit:4 https://deb.debian.org/debian-security bookworm-security InRelease\nIgn:5 https://storage.googleapis.com/cros-packages/132 bookworm InRelease\nHit:6 https://storage.googleapis.com/cros-packages/132 bookworm Release\nIgn:1 https://apt.dockerproject.org/repo ubuntu-bookworm InRelease\nIgn:1 https://apt.dockerproject.org/repo ubuntu-bookworm InRelease\nErr:1 https://apt.dockerproject.org/repo ubuntu-bookworm InRelease\n  Could not resolve 'apt.dockerproject.org'\nReading package lists...\nBuilding dependency tree...\nReading state information...\n54 packages can be upgraded. Run 'apt list --upgradable' to see them.", error="\nWARNING: apt does not have a stable CLI interface. Use with caution in scripts.\n\nW: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-bookworm/InRelease  Could not resolve 'apt.dockerproject.org'\nW: Some index files failed to download. They have been ignored, or old ones used instead."
subprocess: About to execute the cmd: DEBIAN_FRONTEND=noninteractive /usr/bin/apt install -y aptitude colorized-logs dconf-editor evince flameshot gnome-screenshots gnome-tweaks emacs-mozc, emacs-mozc-bin, ibus-mozc, mozc-utils, mozc-server googleearth-package gtk-recordmydesktop ibus ibus-el indicator-multiload libavahi-compat-libdnssd1 pdftk-java pidgin psensor python-software-properties ptex-base ptex-bin sysinfo synaptic xbindkeys xsel whois bash_return_code=100, output='Reading package lists...\nBuilding dependency tree...\nReading state information...\nPackage googleearth-package is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\n\nPackage ibus-el is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\n\nPackage ptex-bin is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\nHowever the following packages replace it:\n  texlive-binaries\n\nPackage gtk-recordmydesktop is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\n\nPackage python-software-properties is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\nHowever the following packages replace it:\n  software-properties-common', error="\nWARNING: apt does not have a stable CLI interface. Use with caution in scripts.\n\nE: Unable to locate package gnome-screenshots\nE: Unable to locate package emacs-mozc,\nE: Unable to locate package emacs-mozc-bin,\nE: Unable to locate package ibus-mozc,\nE: Unable to locate package mozc-utils,\nE: Package 'googleearth-package' has no installation candidate\nE: Package 'gtk-recordmydesktop' has no installation candidate\nE: Package 'ibus-el' has no installation candidate\nE: Unable to locate package indicator-multiload\nE: Package 'python-software-properties' has no installation candidate\nE: Package 'ptex-bin' has no installation candidate\nE: Unable to locate package sysinfo"
subprocess: About to execute the cmd: /usr/bin/apt-cache policy aptitude colorized-logs dconf-editor evince flameshot gnome-screenshots gnome-tweaks emacs-mozc, emacs-mozc-bin, ibus-mozc, mozc-utils, mozc-server googleearth-package gtk-recordmydesktop ibus ibus-el indicator-multiload libavahi-compat-libdnssd1 pdftk-java pidgin psensor python-software-properties ptex-base ptex-bin sysinfo synaptic xbindkeys xsel whois
```

**Comment by 130s** [comment]
<details><summary>After a SUCO ran on opFyde-rpi5, `mozc` didn't get installed.</summary>

```
:
Installing by apt: ['aptitude', 'colorized-logs', 'dconf-editor', 'evince', 'flameshot', 'gnome-screenshots', 'gnome-tweaks', 'emacs-mozc, emacs-mozc-bin, ibus-mozc, mozc-utils, mozc-server', 'googleearth-package', 'gtk-recordmydesktop', 'ibus', 'ibus-el', 'indicator-multiload', 'libavahi-compat-libdnssd1', 'pdftk-java', 'pidgin', 'psensor', 'python-software-properties', 'ptex-base', 'ptex-bin', 'sysinfo', 'synaptic', 'xbindkeys', 'xsel', 'whois']
subprocess: About to execute the cmd: /usr/bin/apt update   bash_return_code=0, output="Ign:1 https://apt.dockerproject.org/repo ubuntu-bookworm InRelease\nHit:2 https://deb.debian.org/debian bookworm InRelease\nHit:3 https://deb.debian.org/debian bookworm-updates InRelease\nHit:4 https://deb.debian.org/debian-security bookworm-security InRelease\nIgn:5 https://storage.googleapis.com/cros-packages/132 bookworm InRelease\nHit:6 https://storage.googleapis.com/cros-packages/132 bookworm Release\nIgn:1 https://apt.dockerproject.org/repo ubuntu-bookworm InRelease\nIgn:1 https://apt.dockerproject.org/repo ubuntu-bookworm InRelease\nErr:1 https://apt.dockerproject.org/repo ubuntu-bookworm InRelease\n  Could not resolve 'apt.dockerproject.org'\nReading package lists...\nBuilding dependency tree...\nReading state information...\n54 packages can be upgraded. Run 'apt list --upgradable' to see them.", error="\nWARNING: apt does not have a stable CLI interface. Use with caution in scripts.\n\nW: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-bookworm/InRelease  Could not resolve 'apt.dockerproject.org'\nW: Some index files failed to download. They have been ignored, or old ones used instead."
subprocess: About to execute the cmd: DEBIAN_FRONTEND=noninteractive /usr/bin/apt install -y aptitude colorized-logs dconf-editor evince flameshot gnome-screenshots gnome-tweaks emacs-mozc, emacs-mozc-bin, ibus-mozc, mozc-utils, mozc-server googleearth-package gtk-recordmydesktop ibus ibus-el indicator-multiload libavahi-compat-libdnssd1 pdftk-java pidgin psensor python-software-properties ptex-base ptex-bin sysinfo synaptic xbindkeys xsel whois bash_return_code=100, output='Reading package lists...\nBuilding dependency tree...\nReading state information...\nPackage googleearth-package is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\n\nPackage ibus-el is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\n\nPackage ptex-bin is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\nHowever the following packages replace it:\n  texlive-binaries\n\nPackage gtk-recordmydesktop is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\n\nPackage python-software-properties is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\nHowever the following packages replace it:\n  software-properties-common', error="\nWARNING: apt does not have a stable CLI interface. Use with caution in scripts.\n\nE: Unable to locate package gnome-screenshots\nE: Unable to locate package emacs-mozc,\nE: Unable to locate package emacs-mozc-bin,\nE: Unable to locate package ibus-mozc,\nE: Unable to locate package mozc-utils,\nE: Package 'googleearth-package' has no installation candidate\nE: Package 'gtk-recordmydesktop' has no installation candidate\nE: Package 'ibus-el' has no installation candidate\nE: Unable to locate package indicator-multiload\nE: Package 'python-software-properties' has no installation candidate\nE: Package 'ptex-bin' has no installation candidate\nE: Unable to locate package sysinfo"
subprocess: About to execute the cmd: /usr/bin/apt-cache policy aptitude colorized-logs dconf-editor evince flameshot gnome-screenshots gnome-tweaks emacs-mozc, emacs-mozc-bin, ibus-mozc, mozc-utils, mozc-server googleearth-package gtk-recordmydesktop ibus ibus-el indicator-multiload libavahi-compat-libdnssd1 pdftk-java pidgin psensor python-software-properties ptex-base ptex-bin sysinfo synaptic xbindkeys xsel whois
```
</details>

I see these errors.

```
E: Unable to locate package gnome-screenshots
E: Unable to locate package emacs-mozc,
E: Unable to locate package emacs-mozc-bin,
E: Unable to locate package ibus-mozc,
E: Unable to locate package mozc-utils,
E: Package 'googleearth-package' has no installation candidate
E: Package 'gtk-recordmydesktop' has no installation candidate
E: Package 'ibus-el' has no installation candidate
E: Unable to locate package indicator-multiload
E: Package 'python-software-properties' has no installation candidate
E: Package 'ptex-bin' has no installation candidate
E: Unable to locate package sysinfo"
```

**Comment by 130s** [comment]
I guess it's not just `mozc` that hasn't got installed. Almost/All pkgs that are meant to be installed by `_DEBIAN_DEB_DEPS` are not installed.

```
subprocess: About to execute the cmd: /usr/bin/apt-cache policy aptitude colorized-logs dconf-editor evince flameshot gnome-screenshots gnome-tweaks googleearth-package gtk-recordmydesktop ibus ibus-el in
dicator-multiload libavahi-compat-libdnssd1 pdftk-java pidgin psensor python-software-properties ptex-base ptex-bin sysinfo synaptic xbindkeys xsel whois emacs-mozc emacs-mozc-bin ibus-mozc mozc-utils-gui
 mozc-server                                                                                          
bash_return_code=0, output='aptitude:\n  Installed: (none)\n  Candidate: 0.8.13-5\n  Version table:\n     0.8.13-5 500\n        500 https://deb.debian.org/debian bookworm/main arm64 Packages\ncolorized-lo
gs:\n  Installed: (none)\n  Candidate: 2.6-1\n  Version table:\n     2.6-1 500\n        500 https://deb.debian.org/debian bookworm/main arm64 Packages\ndconf-editor:\n  Installed: (none)\n  Candidate: 43.
0-1\n  Version table:\n     43.0-1 500\n        500 https://deb.debian.org/debian bookworm/main arm64 Packages\nevince:\n  Installed: (none)\n  Candidate: 43.1-2+b1\n  Version table:\n     43.1-2+b1 500\n
        500 https://deb.debian.org/debian bookworm/main arm64 Packages\nflameshot:\n  Installed: (none)\n  Candidate: 12.1.0-2\n  Version table:\n     12.1.0-2 500\n        500 https://deb.debian.org/debi
an bookworm/main arm64 Packages\ngnome-tweaks:\n  Installed: (none)\n  Candidate: 42~beta-4\n  Version table:\n     42~beta-4 500\n        500 https://deb.debian.org/debian bookworm/main arm64 Packages\ng
oogleearth-package:\n  Installed: (none)\n  Candidate: (none)\n  Version table:\ngtk-recordmydesktop:\n  Installed: (none)\n  Candidate: (none)\n  Version table:\nibus:\n  Installed: (none)\n  Candidate: 
1.5.27-5\n  Version table:\n     1.5.27-5 500\n        500 https://deb.debian.org/debian bookworm/main arm64 Packages\nibus-el:\n  Installed: (none)\n  Candidate: (none)\n  Version table:\nlibavahi-compat
-libdnssd1:\n  Installed: (none)\n  Candidate: 0.8-10+deb12u1\n  Version table:\n     0.8-10+deb12u1 500\n        500 https://deb.debian.org/debian bookworm/main arm64 Packages\npdftk-java:\n  Installed: 
(none)\n  Candidate: 3.3.2-1\n  Version table:\n     3.3.2-1 500\n        500 https://deb.debian.org/debian bookworm/main arm64 Packages\npidgin:\n  Installed: (none)\n  Candidate: 2.14.12-1\n  Version ta
ble:\n     2.14.12-1 500\n        500 https://deb.debian.org/debian bookworm/main arm64 Packages\npsensor:\n  Installed: (none)\n  Candidate: 1.1.5-1.4\n  Version table:\n     1.1.5-1.4 500\n        500 h
ttps://deb.debian.org/debian bookworm/main arm64 Packages\npython-software-properties:\n  Installed: (none)\n  Candidate: (none)\n  Version table:\nptex-base:\n  Installed: (none)\n  Candidate: 1:2.5-3.1\
n  Version table:\n     1:2.5-3.1 500\n        500 https://deb.debian.org/debian bookworm/main arm64 Packages\nptex-bin:\n  Installed: (none)\n  Candidate: (none)\n  Version table:\nsynaptic:\n  Installed
: (none)\n  Candidate: 0.91.3\n  Version table:\n     0.91.3 500\n        500 https://deb.debian.org/debian bookworm/main arm64 Packages\nxbindkeys:\n  Installed: (none)\n  Candidate: 1.8.7-2\n  Version t
able:\n     1.8.7-2 500\n        500 https://deb.debian.org/debian bookworm/main arm64 Packages\nxsel:\n  Installed: (none)\n  Candidate: 1.2.0+git9bfc13d.20180109-4\n  Version table:\n     1.2.0+git9bfc1
3d.20180109-4 500\n        500 https://deb.debian.org/debian bookworm/main arm64 Packages\nwhois:\n  Installed: (none)\n  Candidate: 5.5.17\n  Version table:\n     5.5.17 500\n        500 https://deb.debi
an.org/debian bookworm/main arm64 Packages\nemacs-mozc:\n  Installed: (none)\n  Candidate: 2.28.4715.102+dfsg-2.2+deb12u1\n  Version table:\n     2.28.4715.102+dfsg-2.2+deb12u1 500\n        500 https://de
b.debian.org/debian bookworm/main arm64 Packages\nemacs-mozc-bin:\n  Installed: (none)\n  Candidate: 2.28.4715.102+dfsg-2.2+deb12u1\n  Version table:\n     2.28.4715.102+dfsg-2.2+deb12u1 500\n        500 
https://deb.debian.org/debian bookworm/main arm64 Packages\nibus-mozc:\n  Installed: (none)\n  Candidate: 2.28.4715.102+dfsg-2.2+deb12u1\n  Version table:\n     2.28.4715.102+dfsg-2.2+deb12u1 500\n       
 500 https://deb.debian.org/debian bookworm/main arm64 Packages\nmozc-utils-gui:\n  Installed: (none)\n  Candidate: 2.28.4715.102+dfsg-2.2+deb12u1\n  Version table:\n     2.28.4715.102+dfsg-2.2+deb12u1 50
0\n        500 https://deb.debian.org/debian bookworm/main arm64 Packages\nmozc-server:\n  Installed: (none)\n  Candidate: 2.28.4715.102+dfsg-2.2+deb12u1\n  Version table:\n     2.28.4715.102+dfsg-2.2+deb
12u1 500\n        500 https://deb.debian.org/debian bookworm/main arm64 Packages', error=''
```

**Comment by 130s** [comment]
On zork16 I just decided to manually install `mozc` https://github.com/kinu-garage/hut_10sqft/issues/1036#issuecomment-3123983144. There are still other `apt` pkgs that are not getting installed via `suco` (but can be installed manually) e.g. `gnome-tweaks` so they can be used as a CoS item for this ticket.

**Comment by 130s** [comment]
Well actually https://github.com/kinu-garage/hut_10sqft/pull/1245 only fixed missing pkgs. Setup still needs to be done manually. Reopening although I don't foresee this to be prioritized soon.
