### ISSUE TITLE
mac1: Init setup list 2023

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#846]
https://github.com/kinu-garage/hut_10sqft/issues/637#issuecomment-1601958065 restored the OS so needs setup. Listing up here, then maybe put those in the init tool later if interested.

# CoS
1. [x] Setup `synergy`.
1. [x] Setup `dropbox`.
1. [x] Update host name.
1. [x] Setup `Google Chrome`.
1. [x] Setup the "Dock" on the Desktop (lots removed).
1. [x] Setup `Google Drive Desktop`.
1. [x] G-Drive desktop sync https://github.com/kinu-garage/hut_10sqft/issues/876
   - Make sure undesired deletion occurs. Rule of thumb https://github.com/kinu-garage/hut_10sqft/issues/501#issuecomment-785476932
   - Set up "`Google Drive`" (Mac local client) so that there's a single folder that both GD and `Dropbox` sync, unlike duplicated folders for GD. Steps that worked are described in https://github.com/kinu-garage/hut_10sqft/issues/563#issue-970932825
1. [ ] Setup `Emacs`.
1. [x] Setup Skype.
1. [x] Google Japanese input.
1. [x] Setup Opera web browser.
2. [x] `brew` https://github.com/kinu-garage/hut_10sqft/issues/846#issuecomment-1666833254
3. [x] `tmux` https://github.com/kinu-garage/hut_10sqft/issues/846#issuecomment-1666833254
1. [x] BOINC setup
1. [x] HASS client
2. [ ] VMWare server
1. [x] Find and setup a LAN printer connection.
2. [x] Teamviewer

**Comment by 130s** [comment]
1. [x] Setup `synergy`.
1. [x] Setup `dropbox`.
1. [x] Update host name.
1. [x] Setup `Google Chrome`.
1. [x] Setup the "Dock" on the Desktop (lots removed).
1. [ ] Setup `Google Drive Desktop`.
1. [ ] Setup `Emacs`.

**Comment by 130s** [comment]
1. [ ] Setup Skype.
1. [ ] Google Japanese input.

**Comment by 130s** [comment]
- [ ] Setup Opera web browser.

**Comment by 130s** [comment]
- [ ] BOINC setup

**Comment by 130s** [comment]
Xcode? Nah. Nope. No more dev on Mac.

**Comment by 130s** [comment]
> - BOINC setup

Done. Added back Rosetta and World Community Grid projects (after SETI sadly terminated).

**Comment by 130s** [comment]
- [ ] HASS client

**Comment by 130s** [comment]
> -  HASS client

Do via appstore. https://apps.apple.com/us/app/home-assistant/id1099568401

https://www.home-assistant.io/installation/macos/ is HASS server, not client, I think.

Upon connecting from HASS Mac client, it didn't let me log on with the same device name complaining there's already an entity with the same name (unless the new one to be renamed, which I didn't want to). I had to delete the previous one from "Mobile App](https://%MYDOMAIN%.ui.nabu.casa/config/integrations/integration/mobile_app#config_entry=012f55c9cf39a4e3165e2bc831a667e8) page.

**Comment by 130s** [comment]
Upon connecting from HASS Mac client, it didn't let me log on with the same device name complaining there's already an entity with the same name (unless the new one to be renamed, which I didn't want to). I had to delete the previous one from "Mobile App](https://%MYDOMAIN%.ui.nabu.casa/config/integrations/integration/mobile_app#config_entry=012f55c9cf39a4e3165e2bc831a667e8) page.

**Comment by 130s** [comment]
1. [ ] Find and setup a LAN printer connection.

**Comment by 130s** [comment]
1. [ ] Make sure undesired deletion occurs. Rule of thumb https://github.com/kinu-garage/hut_10sqft/issues/501#issuecomment-785476932

**Comment by 130s** [comment]
1. [ ] Set up "`Google Drive`" (Mac local client) so that there's a single folder that both GD and `Dropbox` sync, unlike duplicated folders for GD. Steps that worked are described in https://github.com/kinu-garage/hut_10sqft/issues/563#issue-970932825

**Comment by 130s** [comment]
`brew` installed following https://mac.install.guide/homebrew/3.html
```
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
Then installed `tmux` by `brew install tmux`.

**Comment by 130s** [comment]
Moved on to https://github.com/kinu-garage/hut_10sqft/issues/978 as macos is reinstalled again https://github.com/kinu-garage/hut_10sqft/issues/977
