### ISSUE TITLE
Chromebook init setup; `brya` on Lenovo c14

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#890]
Similar to https://github.com/kinu-garage/hut_10sqft/issues/881

- Emacs
   - [x] Linux option
   - [x] Enable Emacs 
   - [x] Japanese on Emacs? https://github.com/kinu-garage/hut_10sqft/issues/880
   - [x] Apply my shared Emacs config
- File systems
   - [x] Sync the files Linux-Emacs saves/modifies. https://github.com/kinu-garage/hut_10sqft/issues/891
   - [x] Mount Google Drive folder on local file system. (After Recovery https://github.com/kinu-garage/hut_10sqft/issues/897#issuecomment-1726829950, G-Drive disappered from `Files`, let alone on the local file system). -> Delegated at https://github.com/kinu-garage/hut_10sqft/issues/898
- [x] Install apps that are used on another Chromebook(s) -> Seems to be done automatically.
- E-books downloaded
   - [ ]  On Kindle -> Chose NOT to install as of 20240112. Ref. https://github.com/kinu-garage/hut_10sqft/issues/882#issuecomment-1890415472
- Input
   - [x] Swap caps <--> ctrl 
   - [ ] Switch EN<-->JP input by cmd, not GUI. https://github.com/kinu-garage/hut_10sqft/issues/892
   - [x] Behavior of switching tabs by `ALT + Tab` only switches forward to the adjacent tab, not the prev. tab. --> https://github.com/kinu-garage/hut_10sqft/issues/890#issuecomment-1712781875
   - [x] Trackpoint speed https://github.com/kinu-garage/hut_10sqft/issues/905
- Japanese input
   - [x] Google Japanese input s/w Ref. https://github.com/kinu-garage/hut_10sqft/issues/517
   - [x] Google Jp input dictionary https://github.com/kinu-garage/hut_10sqft/issues/890#issuecomment-1725217879
- GUI
   - [ ] Mouse cursor doesn't disappear on certain GUI apps incl. Google PlayStore, HASS.
- MOOC watch and learn on it
   - [x] Headset connected
   - [ ] Stylus digitally connected
   - [ ] Stylus physically attached
- [ ] Screen sharing b/w Ubuntu
- [ ] Check best practice about Chromebook https://www.makeuseof.com/tag/tips-first-time-chromebook-user/
- [ ] Else

**Comment by 130s** [comment]
> - Input
>    - [ ] Swap caps <--> ctrl

I saw https://github.com/dnschneid/crouton/issues/811, which seems to have suggested geeky solution back then. Now, I was able to swap from ChromeOS' setting.

**Comment by 130s** [comment]
- [ ] Sync the files Linux-Emacs saves/modifies.

**Comment by 130s** [comment]
>  - Switch EN<-->JP input by cmd, not GUI.

`ctrl-Space` by default switches the language input. However, that collides with  Emacs' "set region" cmd.

**Comment by 130s** [comment]
> * Behavior of switching tabs by `ALT + Tab` only switches forward to the adjacent tab, not the prev. tab.

- Installed `Recent Tabs` Chrome extension https://superuser.com/a/433532/106974
   - Set a shortcut to `ctrl + q`, which I don't think I use on Emacs nor on other apps.
   - o Chrome web browser on other hosts (potentially) gets the same? Newer installed Chrome will certainly get it.
   - x Different operation introduced in my usage.

An issue https://github.com/kinu-garage/hut_10sqft/issues/894 is seen but so far the link b/w the extension is unclear to me.

**Comment by 130s** [comment]
An issue https://github.com/kinu-garage/hut_10sqft/issues/894 is seen but so far the link b/w the extension is unclear to me.

**Comment by 130s** [comment]
> - Google Jp input dictionary

My custom JP dict was easily imported. From OS' setting -> Lang -> Japanese with US keyboard -> (click the expand icon, which takes you to a setting webpage) -> Import.

**Comment by 130s** [comment]
- [x] Mount Google Drive folder on local file system. (After Recovery https://github.com/kinu-garage/hut_10sqft/issues/897#issuecomment-1726829950, G-Drive disappered from `Files`, let alone on the local file system).

**Comment by 130s** [comment]
As in https://github.com/kinu-garage/hut_10sqft/issues/909#issuecomment-1780960256, Powerwash-ed again.

**Comment by 130s** [comment]
> - GUI
>    - [ ] Mouse cursor doesn't disappear on certain GUI apps incl. Google PlayStore, HASS.

With this, and the scrolling issue https://github.com/kinu-garage/hut_10sqft/issues/909 becoming more frequently happening, I'm tempted to Powerwash again just to see if it makes any situation better...

**Comment by 130s** [comment]
Closing as either all items checked or non-blocking items are ticketed separately.

> > * GUI
> >   
> >   * [ ]  Mouse cursor doesn't disappear on certain GUI apps incl. Google PlayStore, HASS.
> 
> With this, and the scrolling issue #909 becoming more frequently happening, I'm tempted to Powerwash again just to see if it makes any situation better...

While that's annoying that is not a big deal for now. Workaround is to relogin or reboot the OS.

**Comment by 130s** [comment]
Immediately after ChromeOS upgrade, OS suggested Linux update was available. W/o knowing what that exactly is (maybe Kernel level? as I've been doing `apt update && apt dist-upgrade` manually) I did it.

**Comment by 130s** [comment]
Weirdly, using a web-based CPU benchmark that I mentioned in [here](https://sliprobotics.atlassian.net/browse/SW-619?atlOrigin=eyJpIjoiOGJjMzA2MTgwZjE4NGVjZjliZjI1OTlhZjRkYTAwZWIiLCJwIjoiaiJ9) and related to https://github.com/kinu-garage/hut_10sqft/issues/1053 i.e. https://silver.urih.com/, brya's score P20K is almost double of p16s' P10K 🤔
