### ISSUE TITLE
Chromebook init setup 2nd-time; kukui (Duet)

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#901]
In https://github.com/kinu-garage/hut_10sqft/issues/898#issuecomment-1729074155 I decided to Powerwash (factory reset) so need to make sure init setup is done.

Similar to C14 setup https://github.com/kinu-garage/hut_10sqft/issues/890.

Req:
- Main usecase: As in https://github.com/kinu-garage/hut_10sqft/issues/885#issuecomment-1703797161, kukui is now reading device (PDF, Kindle).
- Major, obvious difference is Linux should NOT be activated on kukui.
- File system is tight (22.2GB/41.8GB with a single user, almost 25.0GB with 3 users).

Impls
- Account
   - [x] Myself#1
   - [x] Myself#2 https://github.com/kinu-garage/hut_10sqft/issues/882#issuecomment-1731690549
   - [x] Family#1 https://github.com/130s/30y-130s_life/issues/1116#issuecomment-958020415
- [x] Emacs -> No.
- [x] File systems
   - [x] None so far.
- [x] Install apps that are used on another Chromebook(s) -> Seems to be done automatically.
- E-books downloaded
   - [x]  On Kindle https://github.com/kinu-garage/hut_10sqft/issues/882#issuecomment-1890415472
- Input
   - [ ] Swap caps <--> ctrl. Not sure how this is done. Synched from other device?
   - [ ] Switch EN<-->JP input by cmd, not GUI. https://github.com/kinu-garage/hut_10sqft/issues/892
   - [ ] Behavior of switching tabs by `ALT + Tab` only switches forward to the adjacent tab, not the prev. tab. --> https://github.com/kinu-garage/hut_10sqft/issues/890#issuecomment-1712781875
- Japanese input
   - [ ] Google Japanese input s/w Ref. https://github.com/kinu-garage/hut_10sqft/issues/517
   - [ ] Google Jp input dictionary https://github.com/kinu-garage/hut_10sqft/issues/890#issuecomment-1725217879
- MOOC watch and learn on it
   - [ ] Headset connected
   - [ ] Stylus digitally connected
   - [ ] Stylus physically attached
- [ ] Screen sharing b/w Ubuntu
- [ ] Else

**Comment by 130s** [comment]
> - File system is tight (22.2GB/41.8GB)

That was with a single user. Now with 3 users it reaches  almost 25.0GB...

**Comment by 130s** [comment]
No more required items left I guess.
