### ISSUE TITLE
Accessibility of movie contents is volatile

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#906]
- Q. Unclear whether the contents on streaming service will always be available?
   - A. My hypo is "no", any content that is once available on streaming service will potentially disappear. If that's the case that means it's possible we won't be able to watch some of the contents we love an\
d will continue loving.
- Q. Then what about having mp4 server at home?
   - A. Sure, we can think about that.
      - But, the many contents are not available in a replay-able file format (e.g. mp4). With copyrights and business-rights in mind, this may not change drastically.

For such contents, ultimately there's no other way than owning by ourselves. Might as well start now to experiment.

# CoS
- [ ] Know limitations.
- [ ] Know technical requirement
   - [ ] DVD
   - [ ] Blue-Ray
- [ ] Reported the finding to family.

**Comment by 130s** [comment]
- (Subject to be updated) Usecase and requirement is probably something like: I want to get a hold of some, say 100 (definitely don't have to be thousands of), video titles over the next 30 years.
  - (Time req) I want to access any of those title when I want to, within 5 mins on avg, 15 minutes at most (Time that takes since starting to find a content to actually start the content to be played on a monitor).
  - (Physical spacial req) It's reluctantly OK to have a shelf-full of DVDs or any physical media at home or anywhere.

**Comment by 130s** [comment]
- Ripping DVD
   - I tried the last time in 2011. It seems certainly possible (and legal as long the purpose is not commercial) https://www.pcmag.com/how-to/best-free-dvd-rippers (Added 20250519) using either Windows or Ubuntu (on Sony's laptop) but ripping failed with some DVDs, IDK what was the culprit.
- DVD player
   - I do NOT want to rely on a dvd drive of a computer. Ideally I want a DVD reader to be modular, pluggable to other computer. Looks like there are many [USB-pluggable DVD players](https://www.google.com/search?q=dvd+player+usb&rlz=1CAVXIY_enUS1076&oq=dvd+player+usb&gs_lcrp=EgZjaHJvbWUyCQgAEEUYORiABDIHCAEQABiABDIHCAIQABiABDIHCAMQABiABDIHCAQQABiABDIHCAUQABiABDIHCAYQABiABDIHCAcQABiABDIHCAgQABiABDIHCAkQABiABNIBCDQzNzlqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8).
   - Non/Functionalities 2023 USB optical drive.
      https://www.lifewire.com/best-external-optical-drives-4584282
      > ## What are the advantages of an optical drive?
      > With media increasingly moving to digital rather than physical storage solutions, an optical drive may seem outdated. But there are still many reasons to invest in an optical drive, not the least of which is to access older media, a significant percentage of which still hasn't been shifted to a digital/online solution. This is especially true if you have games, videos, photos, or documents backed up on physical media. Optical drives can also be a handy way to create new backups quickly and inexpensively, and some programs require discs for emergency boot tools.
      > - Q. Can you read a DVD in a Blu-Ray drive?: A. Yes, both CDs and DVDs are compatible with Blu-Ray drives, and there are combo drives that can burn discs of all three types as well. By contrast, DVD drives cannot read Blu-Ray media.
      > - Q. How does an optical drive work?: A. Optical drives read and write data to discs using a laser. The laser creates pits in an organic dye layer on the disc's surface to write, the reflected light from which can then be read by photodiodes in the drive and converted back into the original data. The disc spins, allowing the laser to read the tracks on its surface consecutively. If you're not using a CD, dozens of supported YouTube and Spotify channels specialize in Karaoke videos, such as Singtrix and Sing King. These channels are updated regularly and often organized by genre and artist.

**Comment by 130s** [comment]
DLNA seems to be the thing. Seems like there are multiple options on HASS incl. https://www.home-assistant.io/integrations/dlna_dms/

Open questions
- [ ] What h/w for server? RPi4 powerful enough? What spec is suitable.
- [ ] (Esp. with RPi4) Is SD cart or any external storage good enough (e.g. no slow down)?
- [ ] What OS, and server s/w?

**Comment by 130s** [comment]
In https://www.baeldung.com/linux/upnp-dlna-clients there's no mention about server, only client (`vlc` etc.) No server needed? Does client directly refer to file system, get the file and stream over network?

**Comment by 130s** [comment]
> What h/w for server? RPi4 powerful enough? What spec is suitable.

In our HASS, where I haven't done anything specific to DLNA yet, shows 2 devices that are capable of being DMS (Digital Media Server), one of the key components in DLNA if I'm not mistaken. Those are CAX80 (and a Windows tablet that I briefly owned https://github.com/kinu-garage/hut_10sqft/issues/753).

IDK if I want to rely on an already-unstable CAX80 (e.g. https://github.com/kinu-garage/hut_10sqft/issues/775, https://github.com/kinu-garage/hut_10sqft/issues/810) for even more features. But this might be a good starting point to test out DLNA.

**Comment by 130s** [comment]
Nighthawk comes with a feature called `ReadySHARE`, but it's EoS https://www.netgear.com/support/product/readyshare_usb_storage_access/ so we should not depend on it.

**Comment by 130s** [comment]
## Reading Blu-Ray disk on Linux
- Blu-Ray external drive: [Plenty options in about $50 range on amazon.co.jp](https://www.amazon.co.jp/s?k=blu-ray+external+drive&adgrpid=116445816456&hvadid=651157314693&hvdev=c&hvexpln=0&hvlocphy=1009180&hvnetw=g&hvocijid=5901608369899580088--&hvqmt=e&hvrand=5901608369899580088&hvtargid=kwd-331153124564&hydadcr=10265_13606985&jp-ad-ap=0&mcid=67a8afaa604538bcb6d566a6f3a99fbf&tag=googhydr-22&ref=pd_sl_7lhuyqwc15_e)
   - [Multiple formats (incl. CD, DVD) + USB-hub feature](https://www.amazon.co.jp/%E3%80%902025%E9%9D%A9%E6%96%B0%E3%83%A2%E3%83%87%E3%83%AB%E3%80%91-%E3%83%96%E3%83%AB%E3%83%BC%E3%83%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%96-%E3%83%96%E3%83%AB%E3%83%BC%E3%83%AC%E3%82%A4%E3%83%97%E3%83%AC%E3%83%BC%E3%83%A4%E3%83%BC-USB3-0%EF%BC%86Type-C%E4%B8%A1%E6%8E%A5%E7%B6%9A-%E5%A4%96%E4%BB%98%E3%81%91%E3%83%96%E3%83%AB%E3%83%BC%E3%83%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%96/dp/B0F5WNZQQ4/ref=sr_1_6?adgrpid=116445816456&dib=eyJ2IjoiMSJ9.tI-c9m_9i5Z54BWqTDwAmwK2_LkNJTEVvPSVafxRBtG668xpnYZGZcTHR2oc3Yp42CMR4zpu8X5qqWNvPG-McuMb89ZvTW5pYkqWLky89-ak1rmHV9GZpNSDkZMYO7HBTsfETwP5Ea6PsYHxkpbfDT4-Fn2hdL2B_r2QMiYfMNaAjKRITtUmwm0Ahatwpe6HG13E0B4Ud0u-HeZHApLED74sKUVzfZ469x3jUcgwvqbYmze7Hp_zoocNN7H2dFivibl2mkBLCcEMxShjxqNnl5DQvCABnLGOwrZcq5z8KjA.KKXQyHZfecxRcQD4pANsM_l1bjrWU60JsCM9ygTvn-w&dib_tag=se&hvadid=651157314693&hvdev=c&hvexpln=0&hvlocphy=1009180&hvnetw=g&hvocijid=5901608369899580088--&hvqmt=e&hvrand=5901608369899580088&hvtargid=kwd-331153124564&hydadcr=10265_13606985&jp-ad-ap=0&keywords=blu-ray%2Bexternal%2Bdrive&mcid=67a8afaa604538bcb6d566a6f3a99fbf&qid=1749307271&sr=8-6&th=1) w/7k jpy. Nice.
- PlayStation5 comes with a drive capable of both ([wikipedia](https://en.wikipedia.org/wiki/PlayStation_5#:~:text=The%20base%20model%20includes%20an,two%20variants%20were%20launched%20simultaneously.)):
   > The standard model includes an Ultra HD Blu-ray drive supporting Ultra HD Blu-ray, standard Blu-ray, and DVD formats, but not CDs or 3D Blu-rays.[49][75][76] PlayStation 5 game discs can hold up to 100 GB of data, double the capacity of standard Blu-ray discs used for most PlayStation 4 games.[77][78]

## Data generation
- There seems to be multiple software options to rip Blu-Ray on Linux [askubuntu.com#21151 (2011 post though)](https://askubuntu.com/questions/21151/any-way-to-easily-rip-blu-ray-disks)
   - `Handbrake`
      - Operation explained https://www.linuxjournaldigital.com/bluray-ripper-linux/
   - MakeMKV

## Dvd, Blu-Ray country code limitation?
- [Region code explained (thesignatureshop.co.uk)](https://thesignatureshop.co.uk/pages/dvd-region-codes-explained)
   - Takeaways: Almost of each drive, disk has regional code embedded.
- [superuser.com#366533](https://superuser.com/questions/366533/is-the-region-code-setting-a-property-of-the-external-dvd-drive-or-the-os) explains:
   - software solution to get around limitation.
   - confirms having multiple drives of different regional codes should allow a single computer to access disks of multiple different regional codes that correspond to that of drives you have.
- Maybe standard these days is multi-region drive. Get one in one country then buy one in another region code if needed? E.g. [Quora: What's the point of DVD region codes if anyone can buy a multi-region DVD player?](https://www.quora.com/Whats-the-point-of-DVD-region-codes-if-anyone-can-buy-a-multi-region-DVD-player)

**Comment by 130s** [comment]
## DVD drive purchase
### Things to know about the choice of DVD drive
[ref1](https://www.youtube.com/watch?v=Fkf6NMtTAUc)
- ROM or writable?
- USB 3.1 is x20 faster than USB 2.0
- (On my own opinion) USB-c is and will be far more versatile in the future
- Blue-Ray readable additional benefit

### FAQs
- Q. Regional code for Blue-Ray drive? A. Answered myself already https://github.com/kinu-garage/hut_10sqft/issues/906#issuecomment-2952665024
- Q. Can Ubuntu (or even ChromeOS if possible) detect an external Blue-Ray drive? Major products may not explicitly claim the support Linux.
   - [askubuntu.com#1284586](https://askubuntu.com/questions/1284586/external-bluray-drive-not-mounting-20-04-lts) shows OS detects the drive, but in order to mount the media in the drive, `udftools` pkg was needed on 20.04.
   - [Setting up Blu-ray on Ubuntu (linux.org)](https://www.linux.org/threads/setting-up-blu-ray-on-ubuntu.51107/) seems to be able to use Blue-Ray drive on 22.04.
   - Google search Labs says:
      > Yes, Ubuntu can detect an external Blu-Ray drive. Ubuntu, like most modern Linux distributions, includes built-in drivers for handling optical disc drives, including Blu-Ray drives. While major manufacturers may not explicitly advertise support for Linux, the standard drivers included in the operating system typically handle the drive's basic functionality. 

### Alright, requirements for a drive
- Blue-Ray, DVD both supported.
   - Note https://github.com/kinu-garage/hut_10sqft/issues/906#issuecomment-1761082897 says Blue-Ray drive can read DVD while the other way round is not the case. Needs to verify that.
- USB 3+ in USB-c form (i.e. NO to USB 2 and USB-a)
- Reading speed > noise level
- I don't see usecases in writing to a DVD/Blue-Ray media?

### Product options
- [conreruru](https://www.amazon.co.jp/%E6%97%A5%E6%9C%AC%E3%83%A1%E3%83%BC%E3%82%AB%E3%83%BC%E7%99%BA%EF%BC%81%E6%AC%A1%E4%B8%96%E4%BB%A3%E3%83%96%E3%83%AB%E3%83%BC%E3%83%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%96%E5%A4%96%E4%BB%98%E3%81%91%EF%BC%81%E3%81%95%E3%82%89%E3%81%AB%E9%80%9F%E3%81%8F%E3%80%81%E8%BB%BD%E3%81%8F%E3%80%81%E8%96%84%E3%81%8F%E5%AE%89%E5%AE%9A%E6%80%A7%EF%BC%81%E3%80%91%E5%A4%96%E4%BB%98%E3%81%91%E3%83%96%E3%83%AB%E3%83%BC%E3%83%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%96-%E5%86%8D%E7%94%9F%E3%83%BB%E8%AA%AD%E3%81%BF%E8%BE%BC%E3%81%BF%E3%83%BB%E6%9B%B8%E3%81%8D%E8%BE%BC%E3%81%BF%E5%AF%BE%E5%BF%9C-%E3%83%9D%E3%83%BC%E3%82%BF%E3%83%96%E3%83%ABBlu-ray%E3%83%97%E3%83%AC%E3%83%BC%E3%83%A4%E3%83%BC-Windows-OS%E3%83%91%E3%82%BD%E3%82%B3%E3%83%B3%E5%AF%BE%E5%BF%9C/dp/B0F6CKB1G4/ref=sr_1_5?adgrpid=116445816456&dib=eyJ2IjoiMSJ9.dJ_QpRpq64JMyyLk-esSdht7JDmtbhIJGBESDSft9-ZRsuASyC74JrdyxTxUw2iItCJM71QPuqyG_rTIavqa5v_GmkgGdgZMJvbgI1-NIRysE7bhY6Y4QT1wmlyjFxJMTsfETwP5Ea6PsYHxkpbfDYSlQ3sWpEx7nD3os-C1IQyxC34zfON4H25m7RsKq3yeAvVfKHEhSg-xOVk_VQWfap_vBoxhitwKxZir_9u4-5KHw9GBmkyHLHyOul4ko-rwZGtse7B8Cklo0Ef0_KGXtNzJoogZBgjIpAKnYIqcd9U.R7gnfiI-CHlpOM0k9P1KI1V6jtR5jYaHct_3vIPUBNc&dib_tag=se&hvadid=651157314693&hvdev=c&hvexpln=0&hvlocphy=1009180&hvnetw=g&hvocijid=5901608369899580088--&hvqmt=e&hvrand=5901608369899580088&hvtargid=kwd-331153124564&hydadcr=10265_13606985&jp-ad-ap=0&keywords=blu-ray%2Bexternal%2Bdrive&mcid=67a8afaa604538bcb6d566a6f3a99fbf&qid=1750919355&refinements=p_36%3A370000-%2Cp_n_feature_two_browse-bin%3A24490322051%7C24490340051%7C24490355051%7C24490367051&rnid=2150390051&sr=8-5&th=1) seems like a new brand or at least this particular one might be a new product as all review comments are new. Reviewr https://my-best.com/products/5737086 shows it's quiet but not the fastest.
- [Logitech](https://www.amazon.co.jp/dp/B0DMF14J8N?tag=mybest_products_5737086-22&th=1) w/o software (which probably only works on Win/Mac) 13K jpy. 4.1 ⭐ 
- [Buffoloe](https://www.amazon.co.jp/%E3%83%90%E3%83%83%E3%83%95%E3%82%A1%E3%83%AD%E3%83%BC-%E3%83%96%E3%83%AB%E3%83%BC%E3%83%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%96-%E7%B5%A6%E9%9B%BB%E3%82%B1%E3%83%BC%E3%83%96%E3%83%AB%E4%BB%98-%E8%96%84%E5%9E%8B%E3%83%9D%E3%83%BC%E3%82%BF%E3%83%96%E3%83%ABBD-BRXL-PUV6U3-BK/dp/B0BS14XJVH/ref=sr_1_1?adgrpid=116445816456&dib=eyJ2IjoiMSJ9.dJ_QpRpq64JMyyLk-esSdht7JDmtbhIJGBESDSft9-ZRsuASyC74JrdyxTxUw2iItCJM71QPuqyG_rTIavqa5v_GmkgGdgZMJvbgI1-NIRysE7bhY6Y4QT1wmlyjFxJMTsfETwP5Ea6PsYHxkpbfDYSlQ3sWpEx7nD3os-C1IQyxC34zfON4H25m7RsKq3yeAvVfKHEhSg-xOVk_VQWfap_vBoxhitwKxZir_9u4-5KHw9GBmkyHLHyOul4ko-rwZGtse7B8Cklo0Ef0_KGXtNzJoogZBgjIpAKnYIqcd9U.R7gnfiI-CHlpOM0k9P1KI1V6jtR5jYaHct_3vIPUBNc&dib_tag=se&hvadid=651157314693&hvdev=c&hvexpln=0&hvlocphy=1009180&hvnetw=g&hvocijid=5901608369899580088--&hvqmt=e&hvrand=5901608369899580088&hvtargid=kwd-331153124564&hydadcr=10265_13606985&jp-ad-ap=0&keywords=blu-ray%2Bexternal%2Bdrive&mcid=67a8afaa604538bcb6d566a6f3a99fbf&qid=1750919355&refinements=p_36%3A370000-%2Cp_n_feature_two_browse-bin%3A24490322051%7C24490340051%7C24490355051%7C24490367051&rnid=2150390051&sr=8-1&th=1) surprisingly low star 3.7 ⭐.

Went w/Logitech one.

**Comment by 130s** [comment]
# Do I have sufficient DNLA components?

![Image](https://github.com/user-attachments/assets/96c4fb43-15cb-4de1-abf8-ba709d18d2fa)
According to ([computerflicks.blogspot.com](https://computerflicks.blogspot.com/2015/03/what-is-dlna.html)),
- DMC: Controller e.g. cellphone app, HASS
- DMR: Renderer e.g. TV, music player.
   - ? Maybe audio receiver/switch belongs here?
- DMS: Server/Storage.
- DMP: Player? Not yet sure. This concept is introduced in [Hans Beekhuyzen's video](https://www.youtube.com/watch?v=d1KO6NKLmsY) but haven't found anywhere else.

**Comment by 130s** [comment]
>> * DMP: Player? Not yet sure. This concept is introduced in [Hans Beekhuyzen's video](https://www.youtube.com/watch?v=d1KO6NKLmsY) but haven't found anywhere else.

Google Search Labs says:
> A DMP (Digital Media Player) DLNA player is a device that is designed to find and play content from a Digital Media Server (DMS) over a network using the DLNA protocol. Essentially, it's a device that can access and play media files (like photos, music, and videos) stored on other devices on your home network.
>
> Examples of DMPs: Common examples include smart TVs, Blu-ray players, game consoles, and dedicated media players that are DLNA-certified.
>
> How it works: When you have a DLNA-enabled TV, for example, it can act as a DMP. It searches for other DLNA-enabled devices on your network (like a computer or NAS drive) that are configured as DMSs. The TV then displays the available media content, and you can select what you want to play.

Another example Hans mentioned:
- RPi running [`RoPieeeXL`](https://www.youtube.com/watch?v=7qa1xMmMO1w)
- [sMS-200 – SOtM](https://www.sotm-audio.com/sotmwp/english/portfolio-item/sms-200/) <img width="320" height="180" alt="Image" src="https://github.com/user-attachments/assets/76eb8ab0-2581-4d53-bb03-3470e813c783" />
- Integrated in an amplifier, or a receiver.
   - Many brands offer DLNA certified amps/receivers.
   - Nowadays most DLNA Players (and Servers (DMS), Renderers (DMR) can play tracks gapless in between, but worth checking the gapless playback capability before getting/buying.
