### ISSUE TITLE
mac1: Init setup list 202401

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#978]
Prev. https://github.com/kinu-garage/hut_10sqft/issues/846

# CoS
1. [x] Setup `synergy`. https://github.com/kinu-garage/hut_10sqft/issues/978#issuecomment-1887891706
1. [x] Setup `dropbox`.
2. [x] Disable auto-hibernation when the monitor turns off https://github.com/kinu-garage/hut_10sqft/issues/978#issuecomment-1892782081
1. [x] Update host name. -> https://github.com/kinu-garage/hut_10sqft/issues/978#issuecomment-1887918845
1. [x] Setup `Google Chrome`.
1. [x] Setup the "Dock" on the Desktop (lots removed).
1. [x] Find and setup a LAN printer connection.
4. [x] `brew` https://github.com/kinu-garage/hut_10sqft/issues/846#issuecomment-1666833254
5. [x] `tmux` https://github.com/kinu-garage/hut_10sqft/issues/846#issuecomment-1666833254
3. [x] `ssh`
4. [x] App bar to be placed in the way it is not too obstructing. https://github.com/kinu-garage/hut_10sqft/issues/978#issuecomment-1896204722
1. [x] Setup `Google Drive Desktop`  https://github.com/kinu-garage/hut_10sqft/issues/876#issuecomment-1667308358
1. [ ] Setup `Emacs`.
1. [ ] Google Japanese input.
5. [ ] Remove Windows dualboot on EFI
1. [x] HASS client
1. [x] Setup Opera web browser.
1. [ ] Setup Skype.
1. [ ] BOINC setup
2. [ ] Teamviewer
2. [ ] VMWare server
3. [ ] Caps lock <--> CTRL swap to be automated https://github.com/kinu-garage/hut_10sqft/issues/1121

**Comment by 130s** [comment]
https://github.com/kinu-garage/hut_10sqft/issues/978#issuecomment-3312951021
UPDATE 20250919: 1.18.1 released in 2025/08 downloaded, installer .dmg worked but executable requires macOS to be 12+. Turned out 1.18.0 also does that. So went back to 1.14.6.

I see multiple .dmg files on my installer storage for 1.14.6 but only one of them was recognized on mac1 as installable. 

----

synergy macos kept asking security privacy when it launches. It was likely related to I first installed their RC3 then overwrote with synergy1.14. Cleanly installed synergy and rebooted OS like suggested in https://symless.com/synergy/help/how-to-fix-macos-security-and-privacy-accessibility-settings seems to resolve it.

Also mouse cursor didn't fully control in the remote (macos) when I had vertically aligned monitors on Ubuntu side. So I realigned monitors on Ubuntu in the way all monitors aligned horizontally.

**Comment by 130s** [comment]
> - Update host name.

https://apple.stackexchange.com/a/287775/41246
```
sudo scutil --set HostName 130s-mac1
sudo scutil --set LocalHostName 130s-mac1
sudo scutil --set ComputerName 130s-mac1
```

**Comment by 130s** [comment]
Adding a printer brother mfc-l2750dw had never been an issue on mac like https://github.com/130s/30y-130s_life/issues/708#issuecomment-704321450 but this time is stuck.

I'm having an issue in using the printer.
https://support.brother.com/g/b/downloadlist.aspx?c=us&lang=en&prod=mfcl2750dw_us_eu_as&os=10065 says:
> We recommend using AirPrint. If your machine does not support AirPrint, download Brother iPrint&Scan from the App Store.

But adding it with `AirPrint` ends up with:
> Unable to verify the printer on your network.
> Unable to connect to ‘Brother MFC-L2750DW series._ipp._tcp.local.’ due to an error. Would you still like to create the printer?

I rebooted the printer and it works well.

**Comment by 130s** [comment]
Mac not reachable by this :thinking: 
```
`hostname`.local
```

**Comment by 130s** [comment]
> - Setup Google Drive Desktop https://github.com/kinu-garage/hut_10sqft/issues/876#issuecomment-1667308358

I'm wondering if making the entire GoogleDrive local folder available offline is necessary. Without that, if a file under GoogleDrive on another computer gets updated, then on mac1 Dropbox may not update that so that the file on remote G-Drive wouldn't get updated?

Because of this fear, I made the entire `GoogleDrive` folder available offline. Will see.

**Comment by 130s** [comment]
I noticed whenever the display turns off, the computer also hibernates. Maybe this setting needs to be enabled in `Settings` -> `Battery` -> `Power Adapter` -> "Prevent computer from sleeping automatically when the display is off".

Testing now.

**Comment by 130s** [comment]
> Boinc clinet

I couldn't find how to attach projects then ran into the thing called [account manager](https://boinc.berkeley.edu/wiki/Account_managers) on Boinc. So went ahead using [BAM!](https://www.boincstats.com/bam/). So far I'm having an issue to attach existing projects to my AM.

**Comment by 130s** [comment]
> -  App bar to be placed in the way it is not too obstructing.

"`Dock`" is moved to the side following https://www.xda-developers.com/how-to-change-size-and-position-of-dock-on-mac/

**Comment by 130s** [comment]
Turned out `ssh` is missing though I thought it got installed via `brew`. Following https://apple.stackexchange.com/questions/365742/use-openssh-agent-instead-of-the-osx-agent doing `brew install openssh` now.

**Comment by 130s** [comment]
`brew install emacs` has been running for hours and not yet finished. https://stackoverflow.com/questions/14849291/brew-install-emacs-error
Looks like binary installation on `brew` is called `Bottle`, and for Emacs there's no bottle of Emacs for Big Sur https://formulae.brew.sh/formula/emacs

----

<details><summary>IDK how long more it took but looks like installing `emacs` is finally finished</summary>

```
==> Patching
==> ./install.sh --prefix=/private/tmp/rust-20240201-76686-4p4om/rustc-1.75.0-src/cargobootstrap
==> ./configure --sysconfdir=/usr/local/etc --tools=analysis,cargo,clippy,rustdoc,rust-analyzer-proc-macro-srv,rust-demangler,src --llvm-root=/usr/local/opt/llvm --enable-llvm-link
==> make
==> make install
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################################################################################# 100.0%
🍺  /usr/local/Cellar/rust/1.75.0: 39,132 files, 858.5MB, built in 68 minutes 22 seconds
==> Installing emacs dependency: tree-sitter
==> make AMALGAMATED=1
==> make install PREFIX=/usr/local/Cellar/tree-sitter/0.20.9
==> cargo install --path=cli
🍺  /usr/local/Cellar/tree-sitter/0.20.9: 13 files, 13.7MB, built in 2 minutes 15 seconds
==> Installing emacs
==> ./configure --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs/29.2/share/info/emacs --with-gnutls --without-x --w
==> make
==> make install
==> Caveats
To start emacs now and restart at login:
  brew services start emacs
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/emacs/bin/emacs --fg-daemon
==> Summary
🍺  /usr/local/Cellar/emacs/29.2: 4,226 files, 119.2MB, built in 2 minutes 40 seconds
==> Running `brew cleanup emacs`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Caveats
==> emacs
To start emacs now and restart at login:
  brew services start emacs
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/emacs/bin/emacs --fg-daemon
```
</details>

Not sure why it's talking about starting an OS service. No GUI coming up yet.
```
$ /usr/local/opt/emacs/bin/emacs --fg-daemon &
[1] 90725
$ Starting Emacs daemon.
$ ps
  PID TTY           TIME CMD
  409 ttys000    0:00.17 -zsh
10893 ttys000    0:00.01 tmux
10896 ttys001    0:00.11 -zsh
90725 ttys001    0:00.07 /usr/local/opt/emacs/bin/emacs --fg-daemon
10904 ttys002    0:00.10 -zsh
$ emacs &
[2] 90750
$ 
[2]  + suspended (tty output)  emacs
$ ps
  PID TTY           TIME CMD
  409 ttys000    0:00.17 -zsh
10893 ttys000    0:00.01 tmux
10896 ttys001    0:00.12 -zsh
90725 ttys001    0:00.07 /usr/local/opt/emacs/bin/emacs --fg-daemon
90750 ttys001    0:00.02 emacs
10904 ttys002    0:00.10 -zsh
```

**Comment by 130s** [comment]
<details><summary>IDK how long more it took but looks like installing `emacs` is finally finished</summary>

```
==> Patching
==> ./install.sh --prefix=/private/tmp/rust-20240201-76686-4p4om/rustc-1.75.0-src/cargobootstrap
==> ./configure --sysconfdir=/usr/local/etc --tools=analysis,cargo,clippy,rustdoc,rust-analyzer-proc-macro-srv,rust-demangler,src --llvm-root=/usr/local/opt/llvm --enable-llvm-link
==> make
==> make install
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################################################################################# 100.0%
🍺  /usr/local/Cellar/rust/1.75.0: 39,132 files, 858.5MB, built in 68 minutes 22 seconds
==> Installing emacs dependency: tree-sitter
==> make AMALGAMATED=1
==> make install PREFIX=/usr/local/Cellar/tree-sitter/0.20.9
==> cargo install --path=cli
🍺  /usr/local/Cellar/tree-sitter/0.20.9: 13 files, 13.7MB, built in 2 minutes 15 seconds
==> Installing emacs
==> ./configure --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs/29.2/share/info/emacs --with-gnutls --without-x --w
==> make
==> make install
==> Caveats
To start emacs now and restart at login:
  brew services start emacs
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/emacs/bin/emacs --fg-daemon
==> Summary
🍺  /usr/local/Cellar/emacs/29.2: 4,226 files, 119.2MB, built in 2 minutes 40 seconds
==> Running `brew cleanup emacs`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Caveats
==> emacs
To start emacs now and restart at login:
  brew services start emacs
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/emacs/bin/emacs --fg-daemon
```
</details>

Not sure why it's talking about starting an OS service. No GUI coming up yet.
```
$ /usr/local/opt/emacs/bin/emacs --fg-daemon &
[1] 90725
$ Starting Emacs daemon.
$ ps
  PID TTY           TIME CMD
  409 ttys000    0:00.17 -zsh
10893 ttys000    0:00.01 tmux
10896 ttys001    0:00.11 -zsh
90725 ttys001    0:00.07 /usr/local/opt/emacs/bin/emacs --fg-daemon
10904 ttys002    0:00.10 -zsh
$ emacs &
[2] 90750
$ 
[2]  + suspended (tty output)  emacs
$ ps
  PID TTY           TIME CMD
  409 ttys000    0:00.17 -zsh
10893 ttys000    0:00.01 tmux
10896 ttys001    0:00.12 -zsh
90725 ttys001    0:00.07 /usr/local/opt/emacs/bin/emacs --fg-daemon
90750 ttys001    0:00.02 emacs
10904 ttys002    0:00.10 -zsh
```

**Comment by 130s** [comment]
UPDATE 20250919: 1.18.1 released in 2025/08 downloaded, installer .dmg worked but executable requires macOS to be 12+. Turned out 1.18.0 also does that. So went back to 1.14.6.

I see multiple .dmg files on my installer storage for 1.14.6 but only one of them was recognized on mac1 as installable.

**Comment by 130s** [comment]
[Octaine 2.0 Plus](https://octane.webmarks.info/)
- score: 44,498
- Multi core score: 180,922
