### ISSUE TITLE
Digital TODO list is not shared with family

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#986]
# Issue
Digital TODO list is only used by me while task assignees can be other family members. This results in me managing the list for all tasks incl. those that I'm not assigned to.

## Background
I'm heavily relying on `Google Tasks` to track immediate action items, but my spouse doesn't do it, in fact the use of digital tool to keep track of tasks is often the target of criticism for my management (but the way it's done is what I always find invalid though).

While changing the mind of spouse (wow it's actually useful!) is probably one major thing that needs to happen, I don't have much control of other person's mental. More practical thing to do is to make the TODO list accessible without effort (spouse refuses to install any more phone apps).

# CoS
- [ ] Family members can see the TODO list items, without opening (their own) digital devices.
- [ ] Family adult members can add a check (i.e. set "finish" state) on the tasks that are completed.
- [ ] My own TODO list is not visible to family members. The list visible to family members should be the one designated to be shared among the family members.
- [ ] New tasks can be added to the list from each family member's digital device.

**Comment by 130s** [comment]
I'm experimenting a kiosk device in the kitchen using an old Kindle Fire HD8 gen7 https://github.com/kinu-garage/hut_10sqft/issues/971 showing Lovelace. I now added a todo-list card https://www.home-assistant.io/integrations/google_tasks/

Currently there's only limited features.
- o Being able to "check" a task.
- x Too many tasks are shown.
- x Tasks cannot be sorted.

There's a thread https://community.home-assistant.io/t/to-do-list-card/653072 where people are complaining about the limited functionality of todo-list Lovelace Card.

**Comment by 130s** [comment]
With https://github.com/kinu-garage/hut_10sqft/issues/1115 and https://github.com/kinu-garage/hut_10sqft/issues/917#issuecomment-2481253477 this is back on the working stack.
